---
title: "BTSCon + Pnom Data Processing"
author: "Erin M. Buchanan"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}
library(rio)
library(dplyr)
library(tidyr)
```

## Import Language Data

```{r}
lang <- "tr"
native_lang <- "Turkish"
native_other <- NULL

# import participants to mark them
PDF <- import(paste0("05_Data_real/data_processing/output_data/",
                     lang, "_participant_data.csv"))
# table(PDF$meta_language)

# import language thingy
trans <- import(paste0("05_Data_real/native_trans.xlsx"))
trans$listed <- trimws(trans$listed)
trans$listed <- tolower(trans$listed)
trans <- trans %>% 
  select(listed, `Official Translation`) %>% 
  unique()

# mark who is a match 
PDF$native_language <- trimws(PDF$native_language)
PDF$native_language <- tolower(PDF$native_language)
PDF <- PDF %>% 
  left_join(trans %>% 
              select(listed, `Official Translation`), 
            by = c("native_language" = "listed")) %>% 
  dplyr::rename(native_trans = `Official Translation`)

PDF$lang_match <- (PDF$native_trans == native_lang | is.na(PDF$native_trans))

if (!is.null(native_other)){
  PDF$lang_match[PDF$native_trans == native_other] <- TRUE
}

table(PDF$lang_match)

# import data - assumes the project is open
DF <- import(paste0("05_Data_real/data_processing/output_data/", 
                    lang, "_trial_data.csv.gz"))

# import stimulus data
stimuli_data <- import(paste0("04_Procedure/", 
                              lang, "/", 
                              lang, "_words.csv"))
```

## Process Data

```{r}
# add that to the DF 
DF <- DF %>% 
  left_join(
    PDF %>% select(observation, lang_match), 
    by = "observation"
  )

# calculate interesting statistics
  # number of participants overall, split
  # number of usable participants, split

part_stats <- DF %>% 
  group_by(lang_match, keep_participant) %>% 
  select(keep_participant, observation, lang_match) %>% 
  unique() %>% 
  summarize(total = n(), .groups = "keep") %>% 
  mutate(language = lang)

# only usable participants 
  # number of trials overall, split
  # number of usable trials overall, split

trial_stats <- DF %>% 
  filter(keep_participant == "keep") %>% 
  group_by(lang_match, keep) %>% 
  summarize(total = n(), .groups = "keep") %>% 
  mutate(language = lang)

  # percent correct, zRT
item_stats <- DF %>% 
  filter(keep_participant == "keep") %>% 
  mutate(correct = ifelse(is.na(correct), FALSE, correct)) %>% 
  group_by(lang_match, class, observation) %>% 
  summarize(accuracy = sum(correct)/n(), .groups = "keep") %>% 
  group_by(lang_match, class) %>% 
  summarize(accuracy = mean(accuracy),
            total = n(), .groups = "keep") %>% 
  left_join(
    DF %>% 
      filter(keep_participant == "keep") %>% 
      filter(keep == "keep") %>% 
      group_by(lang_match, class) %>% 
      summarize(MZRT = mean(Z_RT),
                SDZRT = sd(Z_RT), .groups = "keep"),
    by = c("lang_match", "class")
  )

```

## Priming Section

```{r}
  # percent correct, zRT, n for the target when related versus unrelated
  # priming scores 
  # match across languages 

# figure out trial type ----
  # only select only a few columns
  priming_trials <- DF %>% 
  # note that we don't exclude trials here because we need to keep 
  # them in order to pair together cue-target
  # they will excluded in a minute 
    select(observation, duration, word, class, correct, 
           Z_RT, fix_sender, timestamp, keep, keep_participant, 
           keep_participant_answered, ended_on, original_duration, lang_match) %>% 
    arrange(observation, fix_sender)
  # add trial code and if it's cue/target
  priming_trials$trial_code <- NA
  priming_trials$which <- NA
  # add that information 
  for (person in unique(priming_trials$observation)){
    
    priming_trials$trial_code[priming_trials$observation == person] <- 
      rep(1:401, each = 2, length.out = length(priming_trials$trial_code[priming_trials$observation == person]))
    
    priming_trials$which[priming_trials$observation == person] <-
      rep(c("cue", "target"), times = 2, 
          length.out = length(priming_trials$trial_code[priming_trials$observation == person]))
    
  }
  
  # pivot wider with information you need
  priming_trials$unique_trial <- paste(priming_trials$observation, 
                                        priming_trials$trial_code, sep = "_")
  # do it with merge because ugh pivot
  priming_wide <- merge(
    priming_trials[priming_trials$which == "cue" , ], #just cues
    priming_trials[priming_trials$which == "target" , ], #just targets
    by = "unique_trial",
    all = T
  )
  # take just what we need
  priming_wide <- priming_wide[ , c("unique_trial", "observation.x", "word.x", 
                                  "class.x", "correct.x", "trial_code.x", 
                                  "duration.y", "word.y", "class.y", "correct.y", 
                                  "Z_RT.y", "keep.y", "keep_participant.y",
                                  "keep_participant_answered.y",
                                  "ended_on.x", "ended_on.y",
                                  "original_duration.y", "lang_match.y")]

  # good names
  colnames(priming_wide) <- c("unique_trial", "observation", "cue_word", 
                            "cue_type", "cue_correct", "trial_order", 
                            "target_duration", "target_word", "target_type", 
                            "target_correct", "target_Z_RT",
                            "keep_target", "keep_participant", 
                            "keep_participant_answered",
                            "cue_end_of_trial", "target_end_of_trial", 
                            "target_original_duration", "lang_match")
  
  # only focus on related-unrelated
  priming_focus <- subset(priming_wide, target_type == "word" & cue_type == "word")
  priming_focus$word_combo <- paste0(priming_focus$cue_word, priming_focus$target_word)
  
  # add if it's related or unrelated
  stimuli_data$word_combo <- paste0(stimuli_data[ , 1], stimuli_data[ , 2])
  priming_focus <- merge(priming_focus, stimuli_data[ , c("type", "word_combo")], 
                    by = "word_combo", all.x = T)
  
  # subset out NAs at some point they will be practice trials
  priming_focus <- subset(priming_focus, !is.na(type))
  
  # calculate the total N versus timeout N
  DF_num_trials <- priming_focus %>% 
    group_by(word_combo, lang_match) %>% 
    summarize(target_correct = sum(target_correct, na.rm = T),
              target_answeredN = sum(target_end_of_trial == "response", na.rm = T), 
              target_timeoutN = sum(target_end_of_trial == "timeout", na.rm = T),
              target_prop_correct = target_correct/target_answeredN,
              cue_correct = sum(cue_correct, na.rm = T),
              cue_answeredN = sum(cue_end_of_trial == "response", na.rm = T), 
              cue_timeoutN = sum(cue_end_of_trial == "timeout", na.rm = T),
              cue_prop_correct = cue_correct/cue_answeredN, .groups = "keep")
  
  DF_num_trials2 <-
    priming_focus %>% 
    filter(keep_participant == "keep") %>%  # keep the participant 
    group_by(word_combo, lang_match) %>% 
    summarize(target_correct_keep = sum(target_correct, na.rm = T),
              target_answeredN_keep = sum(target_end_of_trial == "response", na.rm = T), 
              target_timeoutN_keep = sum(target_end_of_trial == "timeout", na.rm = T),
              target_prop_correct_keep = target_correct_keep/target_answeredN_keep,
              cue_correct_keep = sum(cue_correct, na.rm = T),
              cue_answeredN_keep = sum(cue_end_of_trial == "response", na.rm = T), 
              cue_timeoutN_keep = sum(cue_end_of_trial == "timeout", na.rm = T),
              cue_prop_correct_keep = cue_correct_keep/cue_answeredN_keep, 
              .groups = "keep")
  
  DF_num_trials <- DF_num_trials %>% 
    full_join(DF_num_trials2, 
              by = c("word_combo", "lang_match"))
  
  # subset out NAs they are test / practice trials
  # only correct answers and trials to keep
  priming_Z <- priming_focus %>% 
    filter(!is.na(type)) %>% 
    filter(keep_target == "keep") %>% # to exclude correct trials too short
    filter(target_correct == TRUE) %>% # to make sure only correct trials 
    filter(keep_participant == "keep") # participants to keep
  
# Calculate Statistics ----------------------------------------------------
  
  priming_Z_summary <- priming_Z %>% 
  ##group them by target word and condition related/unrelated
  group_by(word_combo, type, target_word, lang_match) %>% 
  ##create average scores by condition 
  dplyr::summarize(avgRT = mean(target_duration, na.rm = T),
            avgZ_RT = mean(target_Z_RT, na.rm = T),
            target_sample_keep = length(na.omit(target_Z_RT)), 
            seRT = sd(target_duration, na.rm = T)/sqrt(length(na.omit(target_duration))),
            seZ_RT = sd(target_Z_RT, na.rm = T)/sqrt(length(na.omit(target_Z_RT))),
            .groups = "keep") %>% 
    # merge with the number of trials data
    left_join(DF_num_trials, by = c("word_combo", "lang_match")) %>% 
    # deal with duplicates because of translation
    arrange(target_word, type) %>% 
      group_by(type, lang_match) %>% 
      mutate(target_word_unique = make.unique(target_word)) %>% 
    ungroup() %>% 
    ##spread that into wide format so we can subtract
  pivot_wider(names_from = c("type", "lang_match"),
              id_cols = "target_word_unique", 
              values_from = c("avgRT", "avgZ_RT", 
                              "seRT", "seZ_RT", 
                              "target_correct", 
                              "target_answeredN", 
                              "target_timeoutN",
                              "target_prop_correct", 
                              "target_correct_keep", 
                              "target_answeredN_keep",
                              "target_timeoutN_keep", 
                              "target_prop_correct_keep",
                              "cue_correct", 
                              "cue_answeredN", 
                              "cue_timeoutN",
                              "cue_prop_correct", 
                              "cue_correct_keep", 
                              "cue_answeredN_keep",
                              "cue_timeoutN_keep", 
                              "cue_prop_correct_keep", 
                              "target_sample_keep"
                              )) %>% 
  ##create the priming scores by subtracting unrelated - related for that target word only 
  mutate(avgRT_prime_FALSE = avgRT_unrelated_FALSE - avgRT_related_FALSE) %>% 
  mutate(avgZ_prime_FALSE = avgZ_RT_unrelated_FALSE - avgZ_RT_related_FALSE) %>% 
  mutate(avgRT_prime_TRUE = avgRT_unrelated_TRUE - avgRT_related_TRUE) %>% 
  mutate(avgZ_prime_TRUE = avgZ_RT_unrelated_TRUE - avgZ_RT_related_TRUE)
```

## Write Out Data

```{r}
export(item_stats, paste0("10_Presentations/pnom_23/processed_data/", 
                          lang, "_item.csv"), row.names = F)

export(part_stats, paste0("10_Presentations/pnom_23/processed_data/", 
                          lang, "_part.csv"), row.names = F)

export(trial_stats, paste0("10_Presentations/pnom_23/processed_data/", 
                          lang, "_trial.csv"), row.names = F)

export(priming_Z_summary, paste0("10_Presentations/pnom_23/processed_data/", 
                          lang, "_priming.csv"), row.names = F)

beepr::beep()
```

