---
title: "Transition Probs"
author: "Erin M. Buchanan"
date: "5/31/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}
library(rio)
library(dplyr)
library(ggplot2)
```

## The Data

This is pilot data. 

```{r}
DF <- import("../05_Data/output_data/trial_data.csv")
names(DF)
```

## Analysis

```{r}
# exclude participants who can't get them right 
DF <- DF %>% 
  filter(keep_participant == 'keep')

# number of trials
nrow(DF)

# number of participants
length(unique(DF$observation))

# format the data for this analysis
DF <- DF %>% 
  group_by(observation) %>% 
  arrange(timestamp) %>% 
  mutate(transition = paste(lag(class), class, sep = "-")) %>% 
  filter(!grepl("NA", transition))

table(DF$transition)

# overall correct percents
DF %>% 
  group_by(class) %>% 
  summarize(correct_avg = mean(as.numeric(correct), na.rm = T))

# check out probs of getting it right overall
DF %>% 
  group_by(transition) %>% 
  summarize(correct_avg = mean(as.numeric(correct), na.rm = T))

# does this change over trial number
DF$trial_block <- substr(DF$sender_id, 1, 2)
DF$trial_block <- gsub("_", "", DF$trial_block)
DF$trial_block <- as.numeric(DF$trial_block)

DF_trials <- DF %>% 
  group_by(trial_block, transition) %>% 
  summarize(correct_avg = mean(as.numeric(correct), na.rm = T))

DF_trials

ggplot(DF_trials, aes(trial_block, correct_avg, color = transition)) + 
  geom_point() + 
  theme_classic()
```

## Only High People

```{r}
people_80 <- DF %>% 
  group_by(observation, class) %>% 
  summarize(correct = mean(as.numeric(correct), na.rm = T)) %>% 
  filter(correct >= .80) %>% 
  ungroup() %>% 
  group_by(observation) %>% 
  summarize(two = n()) %>% 
  filter(two == 2) %>% 
  pull(observation)

DF_80 <- DF %>% 
  filter(observation %in% people_80)

# number of trials
nrow(DF_80)

# number of participants
length(unique(DF_80$observation))

table(DF_80$transition)

# overall correct percents
DF_80 %>% 
  group_by(class) %>% 
  summarize(correct_avg = mean(as.numeric(correct), na.rm = T))

# check out probs of getting it right overall
DF_80 %>% 
  group_by(transition) %>% 
  summarize(correct_avg = mean(as.numeric(correct), na.rm = T))

DF_80_trials <- DF_80 %>% 
  group_by(trial_block, transition) %>% 
  summarize(correct_avg = mean(as.numeric(correct), na.rm = T))

DF_80_trials

ggplot(DF_80_trials, aes(trial_block, correct_avg, color = transition)) + 
  geom_point() + 
  theme_classic()

```




