---
title: "Visualizations"
author: "Erin M. Buchanan"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}
library(ggplot2)
library(dplyr)
library(rio)
library(tidyr)
library(ggridges)
library(nlme)
library(broom)
```

## Participant Statistics

```{r}
files <- list.files(path = "10_Presentations/btscon_23/processed_data",
                    pattern = "*_part.csv",
                    full.names = TRUE)

list.import <- lapply(files, import)

PDF <- bind_rows(list.import) 

# total participants
sum(PDF$total)

# total usable
PDF %>% 
  filter(keep_participant == "keep") %>% 
  pull(total) %>% 
  sum()

PDF <- PDF %>% na.omit()

# total number of participants 27 languages 
ggplot(
  PDF %>% 
  group_by(language) %>% 
  summarize(total = sum(total)), 
  aes(x = language, 
      y = total)) + 
    geom_bar(stat = "identity") + 
    theme_linedraw() + 
    xlab("Study Language") + 
    ylab("Total Participants") + 
  geom_hline(yintercept = 800)

# number of participants by language match by usable or not by language
ggplot(PDF %>% 
         filter(lang_match == "FALSE"), 
       aes(x = language, y = total, fill = keep_participant)) + 
  geom_bar(position = "fill",
            stat = "identity") + 
  theme_linedraw() + 
  xlab("Study Language") + 
  ylab("Percent Usable") + 
  scale_fill_discrete(name = "Keep Participant", 
                      labels = c("No", "Yes")) + 
  theme(legend.position = "bottom") + 
  ggtitle("Language: No Match")

ggplot(PDF %>% 
         filter(lang_match == "TRUE"), 
       aes(x = language, y = total, fill = keep_participant)) + 
  geom_bar(position = "fill",
            stat = "identity") + 
    theme_linedraw() + 
  xlab("Study Language") + 
  ylab("Percent Usable") + 
  scale_fill_discrete(name = "Keep Participant", 
                      labels = c("No", "Yes")) + 
  theme(legend.position = "bottom") + 
  ggtitle("Language: Match")
```

## Trial Statistics

```{r}
files <- list.files(path = "10_Presentations/btscon_23/processed_data",
                    pattern = "*_trial.csv",
                    full.names = TRUE)

list.import <- lapply(files, import)
TDF <- bind_rows(list.import) %>% 
  na.omit()

# total participants
sum(TDF$total)

# total usable
TDF %>% 
  filter(keep == "keep") %>% 
  pull(total) %>% 
  sum()

# total number of participants 27 languages 
ggplot(
  TDF %>% 
  group_by(language) %>% 
  summarize(total = sum(total)), 
  aes(x = language, 
      y = total)) + 
    geom_bar(stat = "identity") + 
    theme_linedraw() + 
    xlab("Study Language") + 
    ylab("Total Trials") + 
  geom_hline(yintercept = 800)

# number of participants by language match by usable or not by language
ggplot(TDF %>% 
         filter(lang_match == "FALSE"), 
       aes(x = language, y = total, fill = keep)) + 
  geom_bar(position = "fill",
            stat = "identity") + 
  theme_linedraw() + 
  xlab("Study Language") + 
  ylab("Percent Usable") + 
  scale_fill_discrete(name = "Keep Trial", 
                      labels = c("No", "Yes")) + 
  theme(legend.position = "bottom") + 
  ggtitle("Language: No Match")

ggplot(TDF %>% 
         filter(lang_match == "TRUE"), 
       aes(x = language, y = total, fill = keep)) + 
  geom_bar(position = "fill",
            stat = "identity") + 
    theme_linedraw() + 
  xlab("Study Language") + 
  ylab("Percent Usable") + 
  scale_fill_discrete(name = "Keep Trial", 
                      labels = c("No", "Yes")) + 
  theme(legend.position = "bottom") + 
  ggtitle("Language: Match")
```

## Item Statistics

```{r}
files <- list.files(path = "10_Presentations/btscon_23/processed_data",
                    pattern = "*_item.csv",
                    full.names = TRUE)

list.import <- lapply(files, import) 
IDF <- bind_rows(list.import) %>% 
  mutate(language = TDF$language)

ggplot(IDF %>% 
         filter(lang_match == "FALSE"), 
       aes(x = language, y = accuracy, fill = class)) + 
  geom_bar(stat = "identity",
           position = "dodge") + 
  theme_linedraw() + 
  xlab("Study Language") + 
  ylab("Percent Accuracy") + 
  scale_fill_discrete(name = "Trial Type", 
                      labels = c("Nonword", "Word")) + 
  theme(legend.position = "bottom") + 
  coord_cartesian(ylim = c(.75,1)) + 
  ggtitle("Language: No Match")

ggplot(IDF %>% 
         filter(lang_match == "TRUE"), 
       aes(x = language, y = accuracy, fill = class)) + 
  geom_bar(stat = "identity",
           position = "dodge") + 
  theme_linedraw() + 
  xlab("Study Language") + 
  ylab("Percent Accuracy") + 
  scale_fill_discrete(name = "Trial Type", 
                      labels = c("Nonword", "Word")) + 
  theme(legend.position = "bottom") + 
  coord_cartesian(ylim = c(.75,1)) + 
  ggtitle("Language: Match")

ggplot(IDF %>% 
         filter(lang_match == "FALSE"), 
       aes(x = language, y = MZRT, fill = class)) + 
  geom_bar(stat = "identity",
           position = "dodge") + 
  theme_linedraw() + 
  xlab("Study Language") + 
  ylab("Mean Z-Score RT") + 
  scale_fill_discrete(name = "Trial Type", 
                      labels = c("Nonword", "Word")) + 
  theme(legend.position = "bottom")  + 
  ggtitle("Language: No Match")

ggplot(IDF %>% 
         filter(lang_match == "TRUE"), 
       aes(x = language, y = MZRT, fill = class)) + 
  geom_bar(stat = "identity",
           position = "dodge") + 
  theme_linedraw() + 
  xlab("Study Language") + 
  ylab("Mean Z-Score RT") + 
  scale_fill_discrete(name = "Trial Type", 
                      labels = c("Nonword", "Word")) + 
  theme(legend.position = "bottom")  + 
  ggtitle("Language: Match")
```

## Priming Statistics 

```{r}
files <- list.files(path = "10_Presentations/btscon_23/processed_data",
                    pattern = "*_priming.csv",
                    full.names = TRUE)

list.import <- lapply(files, import)
num_rows <- unlist(lapply(list.import, nrow))
languages <- unique(TDF$language)

primeDF <- bind_rows(list.import) %>% 
  mutate(language = rep(languages, times = num_rows)) %>% 
  select(language, 
         target_word_unique,
         avgZ_prime_FALSE, 
         avgZ_prime_TRUE,
         avgZ_RT_related_FALSE, 
         avgZ_RT_related_TRUE,
         avgZ_RT_unrelated_FALSE, 
         avgZ_RT_unrelated_TRUE,
         # target_correct_keep_related_FALSE, 
         # target_correct_keep_related_TRUE,
         # target_correct_keep_unrelated_FALSE,
         # target_correct_keep_unrelated_TRUE,
         target_sample_keep_related_FALSE,
         target_sample_keep_related_TRUE,
         target_sample_keep_unrelated_FALSE,
         target_sample_keep_unrelated_TRUE
         )

nrow(primeDF)

all.20 <- primeDF %>% 
  filter(target_sample_keep_related_FALSE >= 20 & 
         target_sample_keep_related_TRUE >= 20 & 
         target_sample_keep_unrelated_FALSE >= 20 & 
         target_sample_keep_unrelated_TRUE)

# need to pivot
all.20.long <- all.20 %>% 
  select(language, avgZ_prime_FALSE, avgZ_prime_TRUE, target_word_unique) %>% 
  pivot_longer(
    cols = c(avgZ_prime_FALSE, avgZ_prime_TRUE), 
    names_to = "lang_match",
    values_to = "primingRT"
  )

primeDF.long <- bind_rows( 
  primeDF %>% 
  select(language, 
         avgZ_RT_related_FALSE, 
         target_sample_keep_related_FALSE,
         target_word_unique) %>% 
  rename(size = target_sample_keep_related_FALSE, 
         z_RT = avgZ_RT_related_FALSE) %>% 
    mutate(type = "related",
           lang_match = FALSE),
  primeDF %>% 
  select(language, 
         avgZ_RT_unrelated_FALSE, 
         target_sample_keep_unrelated_FALSE,
         target_word_unique) %>% 
  rename(size = target_sample_keep_unrelated_FALSE, 
         z_RT = avgZ_RT_unrelated_FALSE) %>% 
    mutate(type = "unrelated",
           lang_match = FALSE), 
  primeDF %>% 
  select(language, 
         avgZ_RT_related_TRUE, 
         target_sample_keep_related_TRUE,
         target_word_unique) %>% 
  rename(size = target_sample_keep_related_TRUE, 
         z_RT = avgZ_RT_related_TRUE) %>% 
    mutate(type = "related",
           lang_match = TRUE),
  primeDF %>% 
  select(language, 
         avgZ_RT_unrelated_TRUE, 
         target_sample_keep_unrelated_TRUE,
         target_word_unique) %>% 
  rename(size = target_sample_keep_unrelated_TRUE, 
         z_RT = avgZ_RT_unrelated_TRUE) %>% 
    mutate(type = "unrelated",
           lang_match = TRUE)
  ) %>% 
  filter(size >= 20)

# pivot and then do anything with at least 20 
ggplot(all.20.long, 
       aes(y = language, x = primingRT, fill = lang_match)) + 
  geom_density_ridges(alpha = .4,
                      scale = .8) + 
  theme_linedraw() + 
  xlab("Z RT Priming") + 
  ylab("Language") + 
  scale_fill_discrete(name = "Language", 
                      labels = c("No Match", "Match")) + 
  theme(legend.position = "bottom")
  
ggplot(primeDF.long %>% 
         filter(lang_match == "FALSE"), 
       aes(y = language, x = z_RT, fill = type)) + 
  geom_density_ridges(alpha = .4,
                      scale = .8) + 
  theme_linedraw() + 
  xlab("Z RT") + 
  ylab("Language") + 
  scale_fill_discrete(name = "Trial", 
                      labels = c("Related", "Unrelated")) + 
  theme(legend.position = "bottom") + 
  coord_cartesian(xlim = c(-1.1, 1.1)) + 
  ggtitle("Language: No Match")

ggplot(primeDF.long %>% 
         filter(lang_match == "TRUE"), 
       aes(y = language, x = z_RT, fill = type)) + 
  geom_density_ridges(alpha = .4,
                      scale = .8) + 
  theme_linedraw() + 
  xlab("Z RT") + 
  ylab("Language") + 
  scale_fill_discrete(name = "Trial", 
                      labels = c("Related", "Unrelated")) + 
  theme(legend.position = "bottom") + 
  coord_cartesian(xlim = c(-1.1, 1.1)) + 
  ggtitle("Language: Match")

model.prime.all.diff <- lme(
  primingRT ~ lang_match,
  random = list(~1|language),
  data = all.20.long
)

summary(model.prime.all.diff)
coef(model.prime.all.diff)

model.prime.diff <- lme(
  z_RT ~ type,
  random = list(~1|language),
  data = primeDF.long
)

summary(model.prime.diff)

model.prime.diff.match <- lme(
  z_RT ~ type*lang_match,
  random = list(~1|language),
  data = primeDF.long
)

summary(model.prime.diff.match)

model.prime.diff.matchT <- lme(
  z_RT ~ type,
  random = list(~1|language),
  data = primeDF.long %>% 
    filter(lang_match == "TRUE")
)

summary(model.prime.diff.matchT)

model.prime.diff.matchF <- lme(
  z_RT ~ type,
  random = list(~1|language),
  data = primeDF.long %>% 
    filter(lang_match == "FALSE")
)

summary(model.prime.diff.matchF)
```


```{r}
matched <- read.csv("03_Materials/matched_stimuli/matched_stimuli.csv")

primeDF.cross <- bind_rows( 
  primeDF %>% 
  select(language, 
         avgZ_RT_related_FALSE, 
         target_sample_keep_related_FALSE,
         target_word_unique) %>% 
  rename(size = target_sample_keep_related_FALSE, 
         z_RT = avgZ_RT_related_FALSE) %>% 
    mutate(type = "related",
           lang_match = FALSE),
  primeDF %>% 
  select(language, 
         avgZ_RT_unrelated_FALSE, 
         target_sample_keep_unrelated_FALSE,
         target_word_unique) %>% 
  rename(size = target_sample_keep_unrelated_FALSE, 
         z_RT = avgZ_RT_unrelated_FALSE) %>% 
    mutate(type = "unrelated",
           lang_match = FALSE), 
  primeDF %>% 
  select(language, 
         avgZ_RT_related_TRUE, 
         target_sample_keep_related_TRUE,
         target_word_unique) %>% 
  rename(size = target_sample_keep_related_TRUE, 
         z_RT = avgZ_RT_related_TRUE) %>% 
    mutate(type = "related",
           lang_match = TRUE),
  primeDF %>% 
  select(language, 
         avgZ_RT_unrelated_TRUE, 
         target_sample_keep_unrelated_TRUE,
         target_word_unique) %>% 
  rename(size = target_sample_keep_unrelated_TRUE, 
         z_RT = avgZ_RT_unrelated_TRUE) %>% 
    mutate(type = "unrelated",
           lang_match = TRUE)
  ) %>% 
  # for weighted means
  mutate(z_RT = ifelse(is.na(z_RT), 0, z_RT),
         size = ifelse(is.na(size), 0, size)) %>% 
  group_by(type, target_word_unique, language) %>% 
  summarize(z_RT = stats::weighted.mean(z_RT, size, na.rm = T),
            size = sum(size),
            .groups = "keep") %>% 
  filter(size >= 20) %>% 
  pivot_wider(id_cols = c(target_word_unique, language),
              names_from = type, 
              values_from = z_RT) %>% 
  na.omit() %>% 
  mutate(primeZRT = unrelated - related) %>% 
  ungroup()

matched2 <- matched %>% 
  left_join(primeDF.cross %>% filter(language == "ar") %>% 
              select(target_word_unique, primeZRT),
            by = c("ar_target_word_unique" = "target_word_unique")) %>% 
  left_join(primeDF.cross %>% filter(language == "br_pt") %>% 
              select(target_word_unique, primeZRT),
            by = c("pt_br_target_word_unique" = "target_word_unique")) %>%
  left_join(primeDF.cross %>% filter(language == "cs") %>% 
              select(target_word_unique, primeZRT),
            by = c("cs_target_word_unique" = "target_word_unique")) %>%
  left_join(primeDF.cross %>% filter(language == "da") %>% 
              select(target_word_unique, primeZRT),
            by = c("da_target_word_unique" = "target_word_unique")) %>%
  left_join(primeDF.cross %>% filter(language == "de") %>% 
              select(target_word_unique, primeZRT),
            by = c("de_target_word_unique" = "target_word_unique")) %>%
  left_join(primeDF.cross %>% filter(language == "el") %>% 
              select(target_word_unique, primeZRT),
            by = c("el_target_word_unique" = "target_word_unique")) %>%
  left_join(primeDF.cross %>% filter(language == "en") %>% 
              select(target_word_unique, primeZRT),
            by = c("en_target_word_unique" = "target_word_unique")) %>%
  left_join(primeDF.cross %>% filter(language == "es") %>% 
              select(target_word_unique, primeZRT),
            by = c("es_target_word_unique" = "target_word_unique")) %>%
  left_join(primeDF.cross %>% filter(language == "fa") %>% 
              select(target_word_unique, primeZRT),
            by = c("fa_target_word_unique" = "target_word_unique")) %>%
  left_join(primeDF.cross %>% filter(language == "fr") %>% 
              select(target_word_unique, primeZRT),
            by = c("fr_target_word_unique" = "target_word_unique")) %>%
  left_join(primeDF.cross %>% filter(language == "he") %>% 
              select(target_word_unique, primeZRT),
            by = c("he_target_word_unique" = "target_word_unique")) %>%
  left_join(primeDF.cross %>% filter(language == "hu") %>% 
              select(target_word_unique, primeZRT),
            by = c("hu_target_word_unique" = "target_word_unique")) %>%
  left_join(primeDF.cross %>% filter(language == "it") %>% 
              select(target_word_unique, primeZRT),
            by = c("it_target_word_unique" = "target_word_unique")) %>%
  left_join(primeDF.cross %>% filter(language == "ja") %>% 
              select(target_word_unique, primeZRT),
            by = c("ja_target_word_unique" = "target_word_unique")) %>%
  left_join(primeDF.cross %>% filter(language == "ko") %>% 
              select(target_word_unique, primeZRT),
            by = c("ko_target_word_unique" = "target_word_unique")) %>%
  left_join(primeDF.cross %>% filter(language == "pl") %>% 
              select(target_word_unique, primeZRT),
            by = c("pl_target_word_unique" = "target_word_unique")) %>%
  left_join(primeDF.cross %>% filter(language == "pt") %>% 
              select(target_word_unique, primeZRT),
            by = c("pt_target_word_unique" = "target_word_unique")) %>%
  left_join(primeDF.cross %>% filter(language == "ro") %>% 
              select(target_word_unique, primeZRT),
            by = c("ro_target_word_unique" = "target_word_unique")) %>%
  left_join(primeDF.cross %>% filter(language == "ru") %>% 
              select(target_word_unique, primeZRT),
            by = c("ru_target_word_unique" = "target_word_unique")) %>%
  left_join(primeDF.cross %>% filter(language == "sk") %>% 
              select(target_word_unique, primeZRT),
            by = c("sk_target_word_unique" = "target_word_unique")) %>%
  left_join(primeDF.cross %>% filter(language == "tr") %>% 
              select(target_word_unique, primeZRT),
            by = c("tr_target_word_unique" = "target_word_unique")) %>%
  left_join(primeDF.cross %>% filter(language == "ur") %>% 
              select(target_word_unique, primeZRT),
            by = c("ur_target_word_unique" = "target_word_unique")) %>%
  left_join(primeDF.cross %>% filter(language == "zh") %>% 
              select(target_word_unique, primeZRT),
            by = c("zh_target_word_unique" = "target_word_unique")) %>% 
  select(starts_with("primeZRT"), en_cue, en_target)

matched2$prop_work <- apply(matched2 %>% select(-en_cue, -en_target), 1, function(x) sum(x > 0, na.rm = T) / length(na.omit(x)))

ggplot(matched2, aes(x = prop_work)) + 
  theme_linedraw() + 
  geom_histogram(bins = 25, fill = "white", color = "black") + 
  ylab("Frequency") + 
  xlab("Proportion that 'Work'")

matched2 %>% 
  filter(prop_work == 1) %>% 
  select(en_cue, en_target)
```


