---
title: "SPAML Priming Summary Data Outputs"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    code_folding: 'hide'
    self_contained: true
  pdf_document:
    toc: yes
    toc_depth: 4
    latex_engine: xelatex
---

# Set Options

```{r setup}
knitr::opts_chunk$set(
  warning = TRUE, # show warnings during codebook generation
  message = TRUE, # show messages during codebook generation
  error = TRUE, # do not interrupt codebook generation in case of errors,
                # usually better for debugging
  echo = TRUE  # show R code
)
ggplot2::theme_set(ggplot2::theme_bw())

library(rio)
library(labelled)
```

# Prep Data

```{r prepare_codebook}
library(codebook)
codebook_data <- import("../data_processing/output_data/priming_data/sr_prime_summary.csv")

# cat(paste(names(codebook_data), collapse = " = '', \n"))

var_label(codebook_data) <- list(
  target_word_unique = 'The target word shown in the study - if the target was used multiple times due to translation, it was given a .NUMBER at the end to be able to match related to unrelated trials.', 
  avgRT_related = 'The average response latency for related trials - using our exclusion rules for both targets and people. Trials: not too long < 3000 ms, not too short > 160ms, correctly answered; People: must be 18 years old, saw at least 100 trials, correctly answered at least 80% of the trials SEEN for files that just say priming_summary, and ANSWERED for files that use the word _answered_ in their file name.', 
  avgRT_unrelated = 'The average response latency for unrelated trials - using our exclusion rules for both targets and people. Trials: not too long < 3000 ms, not too short > 160ms, correctly answered; People: must be 18 years old, saw at least 100 trials, correctly answered at least 80% of the trials SEEN for files that just say priming_summary, and ANSWERED for files that use the word _answered_ in their file name.', 
  avgZ_RT_related = 'The average Z-scored response latency for related trials - using our exclusion rules for both targets and people. Trials: not too long < 3000 ms, not too short > 160ms, correctly answered; People: must be 18 years old, saw at least 100 trials, correctly answered at least 80% of the trials SEEN for files that just say priming_summary, and ANSWERED for files that use the word _answered_ in their file name.', 
  avgZ_RT_unrelated = 'The average Z-scored response latency for unrelated trials - using our exclusion rules for both targets and people. Trials: not too long < 3000 ms, not too short > 160ms, correctly answered; People: must be 18 years old, saw at least 100 trials, correctly answered at least 80% of the trials SEEN for files that just say priming_summary, and ANSWERED for files that use the word _answered_ in their file name.', 
  seRT_related = 'The standard error for the raw response latency related trials.', 
  seRT_unrelated = 'The standard error for the raw response latency unrelated trials.', 
  seZ_RT_related = 'The standard error for the Z-scored response latency related trials.', 
  seZ_RT_unrelated = 'The standard error for the Z-scored response latency unrelated trials.', 
  
  target_answeredN_related = 'The total number of people who answered the target trials when it was in a related condition.', 
  target_answeredN_unrelated = 'The total number of people who answered the target trials when it was in a unrelated condition.', 
  target_timeoutN_related = 'The total number of people who timed out on the target trials when it was in a related condition.', 
  target_timeoutN_unrelated = 'The total number of people who timed out on the target trials when it was in a unrelated condition.', 
  
  target_correct_keep_related = 'The number of correct answers kept based on trial and person level exclusions in the study for related trials (person level depends on the file you use - if it says _answered_ in the file name, it is the exclusion based on the the number they answered, if not, it\'s based on the number they saw).', 
  target_correct_keep_unrelated = 'The number of correct answers kept based on trial and person level exclusions in the study for unrelated trials (person level depends on the file you use - if it says _answered_ in the file name, it is the exclusion based on the the number they answered, if not, it\'s based on the number they saw).', 
  target_answeredN_keep_related = 'The number of answered trials kept based on trial and person level exclusions in the study for related trials (person level depends on the file you use - if it says _answered_ in the file name, it is the exclusion based on the the number they answered, if not, it\'s based on the number they saw).', 
  target_answeredN_keep_unrelated = 'The number of answered trials kept based on trial and person level exclusions in the study for unrelated trials (person level depends on the file you use - if it says _answered_ in the file name, it is the exclusion based on the the number they answered, if not, it\'s based on the number they saw).', 
  target_timeoutN_keep_related = 'The number of timeout trials kept based on trial and person level exclusions in the study for related trials (person level depends on the file you use - if it says _answered_ in the file name, it is the exclusion based on the the number they answered, if not, it\'s based on the number they saw).', 
  target_timeoutN_keep_unrelated = 'The number of timeout trials kept based on trial and person level exclusions in the study for unrelated trials (person level depends on the file you use - if it says _answered_ in the file name, it is the exclusion based on the the number they answered, if not, it\'s based on the number they saw).', 
  target_prop_correct_keep_related = 'The proportion correct for related trials based on person and trial level exclusions.', 
  target_prop_correct_keep_unrelated = 'The proportion correct for unrelated trials based on person and trial level exclusions.', 
  
target_answeredN_related = 'The total number of people who answered the target trials when it was in a related condition.', 
  target_answeredN_unrelated = 'The total number of people who answered the target trials when it was in a unrelated condition.', 
  target_timeoutN_related = 'The total number of people who timed out on the target trials when it was in a related condition.', 
  target_timeoutN_unrelated = 'The total number of people who timed out on the target trials when it was in a unrelated condition.', 
  
  cue_correct_keep_related = 'The number of correct answers kept based on trial and person level exclusions in the study for related trials (person level depends on the file you use - if it says _answered_ in the file name, it is the exclusion based on the the number they answered, if not, it\'s based on the number they saw).', 
  cue_correct_keep_unrelated = 'The number of correct answers kept based on trial and person level exclusions in the study for unrelated trials (person level depends on the file you use - if it says _answered_ in the file name, it is the exclusion based on the the number they answered, if not, it\'s based on the number they saw).', 
  cue_answeredN_keep_related = 'The number of answered trials kept based on trial and person level exclusions in the study for related trials (person level depends on the file you use - if it says _answered_ in the file name, it is the exclusion based on the the number they answered, if not, it\'s based on the number they saw).', 
  cue_answeredN_keep_unrelated = 'The number of answered trials kept based on trial and person level exclusions in the study for unrelated trials (person level depends on the file you use - if it says _answered_ in the file name, it is the exclusion based on the the number they answered, if not, it\'s based on the number they saw).', 
  cue_timeoutN_keep_related = 'The number of timeout trials kept based on trial and person level exclusions in the study for related trials (person level depends on the file you use - if it says _answered_ in the file name, it is the exclusion based on the the number they answered, if not, it\'s based on the number they saw).', 
  cue_timeoutN_keep_unrelated = 'The number of timeout trials kept based on trial and person level exclusions in the study for unrelated trials (person level depends on the file you use - if it says _answered_ in the file name, it is the exclusion based on the the number they answered, if not, it\'s based on the number they saw).', 
  cue_prop_correct_keep_related = 'The proportion correct for related trials based on person and trial level exclusions.', 
  cue_prop_correct_keep_unrelated = 'The proportion correct for unrelated trials based on person and trial level exclusions.',  

  target_sample_keep_related = 'The final number of trials used in the Z-score average calculation.', 
  target_sample_keep_unrelated = 'The final number of trials used in the Z-score average calculation.', 
  avgRT_prime = 'The subtraction of the raw response latency for unrelated minus the raw response latency for related.', 
  avgZ_prime = 'The subtraction of the Z-scored response latency for unrelated minus the Z-scored latency for related.')

metadata(codebook_data)$name <- "Semantic Priming Across Many Languages Priming Summary Data"
metadata(codebook_data)$description <- "This dataset includes the summarized results of the priming trials, the number of trials for both cue and target, and other descriptive information. 

This codebook works for all files that say _summary_ in their name. If the file contains:

- _answered_: the exclusions are based on participants who made at least 80% correct by using number correct divided by number answered.
- does not say answered: the exclusions are based on participants who made at least 80% correct by using number correct divided by the number seen.
- _no2.5_: the Z-scores above 2.5 were excluded before any calculations. 
- _no3.0_: the Z-scores above 3.0 were excluded before any calculations. 
- Does not mention a number: all Z-scores are included. 
- Therefore, six combinations of files are included based on which scoring criterion and Z-score exclusion level you want to use. The Z-score exclusion level files do not contain all columns - the repetitive number of trial columns are excluded from those files (i.e., the number answered is the same no matter which Z-scored file is used, so it's only in the overall summary for each answered and non-answered file). The exclusions for sample size can be confusing, so we include a summary chart below. 

Semantic priming has been studied for nearly 50 years across various experimental manipulations and theoretical frameworks. These studies provide insight into the cognitive underpinnings of semantic representations in both healthy and clinical populations; however, they have suffered from several issues including generally low sample sizes and a lack of diversity in linguistic implementations. Here, we will test the size and the variability of the semantic priming effect across ten languages by creating a large database of semantic priming values, based on an adaptive sampling procedure. Differences in response latencies between related word-pair conditions and unrelated word-pair conditions (i.e., difference score confidence interval is greater than zero) will allow quantifying evidence for semantic priming, whereas improvements in model fit with the addition of a random intercept for language will provide support for variability in semantic priming across languages."
metadata(codebook_data)$identifier <- "https://doi.org/10.5281/zenodo.10888833"
metadata(codebook_data)$creator <- "Erin M. Buchanan"
metadata(codebook_data)$citation <- "Buchanan, E., Cuccolo, K., Heyman, T., Iyer, A., Coles, N., Lewis Jr, N., Peters, K., van Berkel, N., Taylor, J., Van't Veer, A. E., Montefinese, M., Valentine, K. D., Maxwell, N., Türkan, B. N., Williams, G., Oliveros-Chacana, J. C., Röer, J., Fini, C., Acar, O., … Lewis, S. C. (2024). SemanticPriming/SPAML: SPAML v1 Data Release (v1.0.0) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.10888833"
metadata(codebook_data)$url <- "https://github.com/SemanticPriming/SPAML/releases/"
metadata(codebook_data)$datePublished <- "2024-05-01"
metadata(codebook_data)$temporalCoverage <- "2022-2024" 
metadata(codebook_data)$spatialCoverage <- "Online" 
```

# Summary Chart

```{r}
library(flextable)
library(rio)
summary_table <- import("sample_size_summary.xlsx")
flextable(
  summary_table
) %>% 
  add_footer_lines("Note. These columns also apply for cue values, and the star indicates either an unrelated or related trial for calculation.") %>%
  theme_zebra()
```

# Create codebook

```{r codebook}
codebook(codebook_data)
```
