---
title: "SPAML Participant Data Outputs"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    code_folding: 'hide'
    self_contained: true
  pdf_document:
    toc: yes
    toc_depth: 4
    latex_engine: xelatex
---

# Set Options

```{r setup}
knitr::opts_chunk$set(
  warning = TRUE, # show warnings during codebook generation
  message = TRUE, # show messages during codebook generation
  error = TRUE, # do not interrupt codebook generation in case of errors,
                # usually better for debugging
  echo = TRUE  # show R code
)
ggplot2::theme_set(ggplot2::theme_bw())

library(rio)
library(labelled)
```

# Prep Data

```{r prepare_codebook}
library(codebook)
codebook_data <- import("../data_processing/output_data/participant_data/sr_participant_data.csv")

# cat(paste(names(codebook_data), collapse = " = '', \n"))

var_label(codebook_data) <- list(
  observation = "Unique participant ID number.",
  duration_demographics = "The duration in milliseconds of the entire trial from time shown to time end - for the demographics form page.",
  time_run_demographics = "The time in milliseconds from the start of the experiment it took to run (start to display) the trial - for the demographics form page.",
  time_render_demographics = "The time in milliseconds from the start of the experiment it took to render (prepare, get ready for) the trial - for the demographics form page.",
  time_show_demographics = "The time in milliseconds from the start of the experiment it took to show the trial on the screen to the participant - for the demographics form page.",
  time_end_demographics = "The time in milliseconds from the start of the experiment it took to end the current trial - for the demographics form page.",
  time_commit_demographics = "The time in milliseconds from the start of the experiment it took to save the current trial - for the demographics form page.",
  timestamp_demographics = "The approximate timestamp of the trial in UTC server time - for the demographics form page.",
  time_switch_demographics = "The time in milliseconds from the start of the experiment it took to switch between the previous trial and the current trial - for the demographics form page.",
  please_tell_us_your_gender = "A multiple choice option for the gender of the participant. All answer choices were in the target language, but are presented in English equivalents here.",
  which_year_were_you_born = "A numeric entry box for the year of birth for the participant.",
  please_tell_us_your_education_level = "A multiple choice option for the education level of the participant. All answer choices were in the target language, but are presented in English equivalents here.",
  native_language = "An open choice answer box for the native language of the participant.",
  duration_consent = "The duration in milliseconds of the entire trial from time shown to time end - for the consent form page.",
  time_run_consent = "The time in milliseconds from the start of the experiment it took to run (start to display) the trial - for the consent form page.",
  time_render_consent = "The time in milliseconds from the start of the experiment it took to render (prepare, get ready for) the trial - for the consent form page.",
  time_show_consent = "The time in milliseconds from the start of the experiment it took to show the trial on the screen to the participant - for the consent form page.",
  time_end_consent = "The time in milliseconds from the start of the experiment it took to end the current trial - for the consent form page.",
  time_commit_consent = "The time in milliseconds from the start of the experiment it took to save the current trial - for the consent form page.",
  timestamp_consent = "The approximate timestamp of the trial in UTC server time - for the consent form page.",
  time_switch_consent = "The time in milliseconds from the start of the experiment it took to switch between the previous trial and the current trial - for the consent form page.",
  url_lab = "The lab code for the PSA member that ran the study.",
  meta_labjs_version = "The version of labjs used in the study.",
  meta_user_agent = "The browser the participant used in the study.",
  meta_platform = "The operating system of the computer used in the experiment.",
  meta_language = "The default language set for the browser the participant used in the study.",
  meta_locale = "The location of the browser the participant used in the study.",
  meta_time_zone = "The timezone set for the browser/computer the participant used in the study.",
  meta_timezone_offset = "The time zone offset from UTC time.",
  meta_screen_width = "The width of the screen in pixels.",
  meta_screen_height = "The height of the screen in pixels.",
  meta_scroll_height = "The height of the scroll bar.",
  meta_scroll_width = "The width of the scroll bar.", 
  meta_window_inner_width = "The width of the browser window in pixels.",
  meta_window_inner_height = "The height of the browser window in pixels.",
  meta_device_pixel_ratio = "The ratio of width to height of the screen in pixels.",
  meta_labjs_build_flavor = "The version build of the labjs version - usually production.",
  meta_labjs_build_commit = "The commit version of the labjs build.",
  keep = 'If that participant met the participant level exclusion criteria: they had to be at least 18, see at least 100 trials, and correctly answer 80% of the trials SEEN.', 
  keep_answered = 'If that participant met the participant level exclusion criteria: they had to be at least 18, see at least 100 trials, and correctly answer 80% of the trials ANSWERED.',
  n_trials = 'Number of trials seen in the study. ', 
  n_correct = 'Number of trials correctly answered in the study.', 
  p_correct = 'Proportion correct of total correct answers divided by number of trials seen.', 
  n_answered = 'Number of trials answered in the study (excludes timeouts). ', 
  p_correct_answered = 'Proportion of trials correctly answered given the number of trials answered in the study.', 
  start = 'The first timestamp of the study. ', 
  end = 'The last timestamp of the study.', 
  study_length = "Length of the study in minutes. Please note that if a participant's computer went to sleep during the study, it would pause the study, but given the next timestamp would still calculate time elapsed from the previous timestamp. Therefore, very long response times likely indicate participants that quit the study but did not close the browser window for a long time.")

metadata(codebook_data)$name <- "Semantic Priming Across Many Languages Participants Level Data (Example using Serbian Data)"
metadata(codebook_data)$description <- "This dataset contains the summarized participant information, separated by language, for participants involved in the study. The data includes demographic variables, timestamp information for the consent form and demographic page, and the summarized accuracy, trial, and study length for each participant. 

Semantic priming has been studied for nearly 50 years across various experimental manipulations and theoretical frameworks. These studies provide insight into the cognitive underpinnings of semantic representations in both healthy and clinical populations; however, they have suffered from several issues including generally low sample sizes and a lack of diversity in linguistic implementations. Here, we will test the size and the variability of the semantic priming effect across ten languages by creating a large database of semantic priming values, based on an adaptive sampling procedure. Differences in response latencies between related word-pair conditions and unrelated word-pair conditions (i.e., difference score confidence interval is greater than zero) will allow quantifying evidence for semantic priming, whereas improvements in model fit with the addition of a random intercept for language will provide support for variability in semantic priming across languages."
metadata(codebook_data)$identifier <- "https://doi.org/10.23668/psycharchives.7074"
metadata(codebook_data)$creator <- "Erin M. Buchanan"
metadata(codebook_data)$citation <- "Buchanan, E. M., Cuccolo, K., Coles, N. A., Heyman, T., Iyer, A., Lewis, N. A., Jr., … Lewis, S. C. (2021, December 7). Measuring the Semantic Priming Effect Across Many Languages. https://doi.org/10.31219/osf.io/q4fjy"
metadata(codebook_data)$url <- "https://osf.io/wrpj4/"
metadata(codebook_data)$datePublished <- "2023-02-10"
metadata(codebook_data)$temporalCoverage <- "2022-2023" 
metadata(codebook_data)$spatialCoverage <- "Online" 
```

# Create codebook

```{r codebook}
codebook(codebook_data)
```
