---
title: "SPAML Trial Data Outputs"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    code_folding: 'hide'
    self_contained: true
  pdf_document:
    toc: yes
    toc_depth: 4
    latex_engine: xelatex
---

# Set Options

```{r setup}
knitr::opts_chunk$set(
  warning = TRUE, # show warnings during codebook generation
  message = TRUE, # show messages during codebook generation
  error = TRUE, # do not interrupt codebook generation in case of errors,
                # usually better for debugging
  echo = TRUE  # show R code
)
ggplot2::theme_set(ggplot2::theme_bw())

library(rio)
library(labelled)
```

# Prep Data

```{r prepare_codebook}
library(codebook)
codebook_data <- import("../data_processing/output_data/trial_data/sr_trial_data.csv.gz")

# cat(paste(names(codebook_data), collapse = " = '', \n"))

var_label(codebook_data) <- list(
  observation = "Unique participant ID number.",
  fix_sender = "The sender_id column in a sortable format. You can sort the data by observation and this column to ensure it is in trial order.", 
  response = "Participant response to the trial.",
  response_action = "Keypress used to indicate their response to the trial.", 
  ended_on = "How the trial ended (timeout, form submit, completion, response).",
  duration = "The duration in milliseconds of the entire trial from time shown to time end. This variable was set to NA if the trial was incorrectly answered, too long (3000+ms) or too short (<=160ms). The original duration is also preserved.",
  time_run = "The time in milliseconds from the start of the experiment it took to run (start to display) the trial.",
  time_render = "The time in milliseconds from the start of the experiment it took to render (prepare, get ready for) the trial.",
  time_show = "The time in milliseconds from the start of the experiment it took to show the trial on the screen to the participant.",
  time_end = "The time in milliseconds from the start of the experiment it took to end the current trial.",
  time_commit = "The time in milliseconds from the start of the experiment it took to save the current trial.",
  timestamp = "The approximate timestamp of the trial in UTC server time.",
  time_switch = "The time in milliseconds from the start of the experiment it took to switch between the previous trial and the current trial.",
  word = "The string of letters/characters shown on the screen for the trial.",
  class = "The type of stimuli shown on the screen (word or nonword).",
  correct_response = "The correct answer for the trial.",
  correct = "A logical variable indicating if the participant got the trial answer correct.",
  original_duration = "The duration in milliseconds of the entire trial from time shown to time end.",
  Z_RT = 'The Z-scored response latency (by participant) of the duration column.', 
  keep = 'If the trial level data should be kept based on our exclusion rules (not too long < 3000 ms, not too short > 160ms, correctly answered).', 
  keep_participant = 'If the participant should be kept based on our exclusion rules: must be 18 years old, saw at least 100 trials, correctly answered at least 80% of the trials SEEN.', 
  keep_participant_answered = 'If the participant should be kept based on our exclusion rules: must be 18 years old, saw at least 100 trials, correctly answered at least 80% of the trials ANSWERED.')

metadata(codebook_data)$name <- "Semantic Priming Across Many Languages Trial Level Data"
metadata(codebook_data)$description <- "This dataset contains the processed trial data of the data collection from the SPAML project (example in Serbian, but all datasets are the same). The data is presented here in long format, with each trial representing one row in the data. All other trials (consent/demographic screens), fillers, fixation crosses, etc. have been excluded in this version. 

Semantic priming has been studied for nearly 50 years across various experimental manipulations and theoretical frameworks. These studies provide insight into the cognitive underpinnings of semantic representations in both healthy and clinical populations; however, they have suffered from several issues including generally low sample sizes and a lack of diversity in linguistic implementations. Here, we will test the size and the variability of the semantic priming effect across ten languages by creating a large database of semantic priming values, based on an adaptive sampling procedure. Differences in response latencies between related word-pair conditions and unrelated word-pair conditions (i.e., difference score confidence interval is greater than zero) will allow quantifying evidence for semantic priming, whereas improvements in model fit with the addition of a random intercept for language will provide support for variability in semantic priming across languages."
metadata(codebook_data)$identifier <- "https://doi.org/10.5281/zenodo.10888833"
metadata(codebook_data)$creator <- "Erin M. Buchanan"
metadata(codebook_data)$citation <- "Buchanan, E., Cuccolo, K., Heyman, T., Iyer, A., Coles, N., Lewis Jr, N., Peters, K., van Berkel, N., Taylor, J., Van't Veer, A. E., Montefinese, M., Valentine, K. D., Maxwell, N., Türkan, B. N., Williams, G., Oliveros-Chacana, J. C., Röer, J., Fini, C., Acar, O., … Lewis, S. C. (2024). SemanticPriming/SPAML: SPAML v1 Data Release (v1.0.0) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.10888833"
metadata(codebook_data)$url <- "https://github.com/SemanticPriming/SPAML/releases/"
metadata(codebook_data)$datePublished <- "2024-05-01"
metadata(codebook_data)$temporalCoverage <- "2022-2024" 
metadata(codebook_data)$spatialCoverage <- "Online" 
```

# Create codebook

```{r codebook}
codebook(codebook_data)
```
