---
title             : "The title"
shorttitle        : "Title"

author:
  Erin M. Buchanan:
    name: Erin M. Buchanan
    affiliation: '1'
    role:
      - Conceptualization
      - Data curation
      - Formal analysis
      - Funding acquisition
      - Investigation
      - Methodology
      - Project administration
      - Resources
      - Software
      - Supervision
      - Validation
      - Visualization
      - Writing - original draft
      - Writing - review & editing
      - .na.character
    corresponding: yes
    email: ebuchanan@harrisburgu.edu
    address: Enter postal address here
  Kelly Cuccolo:
    name: Kelly Cuccolo
    affiliation: '2'
    role:
      - Project administration
      - Supervision
      - Writing - review & editing
    corresponding: no
    email: cuccolokm@gmail.com
  Tom Heyman:
    name: Tom Heyman
    affiliation: '3'
    role:
      - Conceptualization
      - Data curation
      - Methodology
      - Project administration
      - Validation
      - Writing - review & editing
    corresponding: no
    email: t.d.p.heyman@fsw.leidenuniv.nl
  Niels van Berkel:
    name: Niels van Berkel
    affiliation: '4'
    role:
      - Methodology
      - Project administration
      - Software
      - Writing - review & editing
    corresponding: no
    email: nielsvanberkel@cs.aau.dk
  Nicholas A. Coles:
    name: Nicholas A. Coles
    affiliation: '5'
    role:
      - Validation
      - Writing - review & editing
    corresponding: no
    email: ncoles797@gmail.com
  Aishwarya Iyer:
    name: Aishwarya Iyer
    affiliation: '6'
    role:
      - Project administration
      - Writing - review & editing
    corresponding: no
    email: aishwarya.iyer@res.christuniversity.in
  Kim Peters:
    name: Kim Peters
    affiliation: '7'
    role:
      - Project administration
      - Writing - review & editing
    corresponding: no
    email: k.o.peters2@exeter.ac.uk
  A. E. van 't Veer:
    name: A. E. van 't Veer
    affiliation: '3'
    role:
      - Project administration
      - Writing - review & editing
    corresponding: no
    email: a.e.van.t.veer@fsw.leidenuniv.nl
  Maria Montefinese:
    name: Maria Montefinese
    affiliation: '8'
    role:
      - Conceptualization
      - Investigation
      - Methodology
      - Resources
      - Writing - original draft
      - Writing - review & editing
    corresponding: no
    email: maria.montefinese@gmail.com
  Nicholas P. Maxwell:
    name: Nicholas P. Maxwell
    affiliation: '9'
    role:
      - Conceptualization
      - Investigation
      - Methodology
      - Writing - review & editing
    corresponding: no
    email: nicholas.maxwell@msutexas.edu
  Jack E. Taylor:
    name: Jack E. Taylor
    affiliation: '10'
    role:
      - Conceptualization
      - Methodology
      - Writing - original draft
      - Writing - review & editing
    corresponding: no
    email: Taylor@psych.uni-frankfurt.de
  Kathrene  D. Valentine:
    name: Kathrene  D. Valentine
    affiliation: '11,12'
    role:
      - Conceptualization
      - Methodology
      - Writing - original draft
      - Writing - review & editing
    corresponding: no
    email: kvalentine2@mgh.harvard.edu
  Patrícia Arriaga:
    name: Patrícia Arriaga
    affiliation: '13'
    role:
      - Funding acquisition
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: patricia.arriaga@iscte-iul.pt
  Krystian Barzykowski:
    name: Krystian Barzykowski
    affiliation: '14'
    role:
      - Investigation
      - Resources
      - Supervision
      - Writing - review & editing
    corresponding: no
    email: krystian.barzykowski@uj.edu.pl
  Leanne Boucher:
    name: Leanne Boucher
    affiliation: '15'
    role:
      - Investigation
      - Resources
      - Supervision
      - Writing - review & editing
    corresponding: no
    email: lb1079@nova.edu
  W. M. Collins:
    name: W. M. Collins
    affiliation: '15'
    role:
      - Investigation
      - Resources
      - Supervision
      - Writing - review & editing
    corresponding: no
    email: wc292@nova.edu
  David C. Vaidis:
    name: David C. Vaidis
    affiliation: '16,17'
    role:
      - Investigation
      - Resources
      - Supervision
      - Writing - review & editing
    corresponding: no
    email: david.vaidis@univ-tlse2.fr
  Balazs Aczel:
    name: Balazs Aczel
    affiliation: '18'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: balazs.aczel@gmail.com
  Ali H. Al-Hoorie:
    name: Ali H. Al-Hoorie
    affiliation: '19'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: hoorie_a@rcjy.edu.sa
  Ettore Ambrosini:
    name: Ettore Ambrosini
    affiliation: '8'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: ettore.ambrosini@unipd.it
  Théo Besson:
    name: Théo Besson
    affiliation: '17'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: theo.besson@u-paris.fr
  Debora I. Burin:
    name: Debora I. Burin
    affiliation: '20,21'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: dburin@psi.uba.ar
  Muhammad M. Butt:
    name: Muhammad M. Butt
    affiliation: '22'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: mussaffa@gmail.com
  A. J. Benjamin Clarke:
    name: A. J. Benjamin Clarke
    affiliation: '23'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: "ajb.clarke@gmail.com\r\n "
  Yalda  Daryani:
    name: Yalda  Daryani
    affiliation: '24'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: yaldadaryani@gmail.com 
  Dina  A. S. El-Dakhs :
    name: Dina  A. S. El-Dakhs 
    affiliation: '25'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: ddakhs@psu.edu.sa
  Mahmoud M. Elsherif:
    name: Mahmoud M. Elsherif
    affiliation: '26,27'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: mahmoud.medhat.elsherif@gmail.com
  Maria Fernández-López:
    name: Maria Fernández-López
    affiliation: '28'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: maria.fernandez@uv.es
  Paulo R. S. Ferreira:
    name: Paulo R. S. Ferreira
    affiliation: '29'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: paulorobertosantosferreira@gmail.com
  Raquel M. K. Freitag:
    name: Raquel M. K. Freitag
    affiliation: '30'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: rkofreitag@academico.ufs.br
  Carolina A. Gattei:
    name: Carolina A. Gattei
    affiliation: '20,31'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: carogattei@utdt.edu
  Hendrik Godbersen:
    name: Hendrik Godbersen
    affiliation: '32'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: hendrik.godbersen@fom.de
  Philip A. Grim II:
    name: Philip A. Grim II
    affiliation: '1'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: pgrim@harrisburgu.edu
  Peter Halama:
    name: Peter Halama
    affiliation: '33'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: peter.halama@savba.sk
  Patrik Havan:
    name: Patrik Havan
    affiliation: '33'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: patrik.havan@savba.sk
  Natalia C. Irrazabal:
    name: Natalia C. Irrazabal
    affiliation: '21'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: nirrazabal@psi.uba.ar
  Chris Isloi:
    name: Chris Isloi
    affiliation: '34'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: barbu.chris@gmail.com
  Rebecca K. Iversen:
    name: Rebecca K. Iversen
    affiliation: '35'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: r.k.iversen@ifikk.uio.no
  Yoann Julliard:
    name: Yoann Julliard
    affiliation: '36,37'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: yoannjulliard@protonmail.com
  Aslan Department of Psychology, IIzmir Katip Celebi University, Izmir, Türkiye:
    name: Aslan Department of Psychology, IIzmir Katip Celebi University, Izmir, Türkiye
    affiliation: '38,39'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: aslankaraaslan@gmail.com
  Michal Kohút:
    name: Michal Kohút
    affiliation: '40'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: michal.kohut@truni.sk
  Veronika Kohútová:
    name: Veronika Kohútová
    affiliation: '40'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: veronika.kohutova@truni.sk
  Julija Kos:
    name: Julija Kos
    affiliation: '41'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: julijaakos@gmail.com
  Alexandra I. Kosachenko:
    name: Alexandra I. Kosachenko
    affiliation: '42'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: alleshch7@gmail.com
  Tiago J. S. d. Lima:
    name: Tiago J. S. d. Lima
    affiliation: '43'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: tiago.lima@unb.br
  Matthew HC Mak:
    name: Matthew HC Mak
    affiliation: '44'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: matthew.mak@warwick.ac.uk
  Christina  Manouilidou:
    name: Christina  Manouilidou
    affiliation: '41'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: Christina.Manouilidou@ff.uni-lj.si
  Leonardo A. Marciaga:
    name: Leonardo A. Marciaga
    affiliation: '45'
    role:
      - Validation
      - Visualization
      - Writing - review & editing
    corresponding: no
    email: leonardomarciaga@gmail.com
  Xiaolin M. Melinna:
    name: Xiaolin M. Melinna
    affiliation: '46'
    role:
      - Project administration
      - Resources
      - Writing - review & editing
    corresponding: no
    email: melinna@live.cn
  Jacob F. Miranda:
    name: Jacob F. Miranda
    affiliation: '47'
    role:
      - Investigation
      - Project administration
      - Writing - review & editing
    corresponding: no
    email: jacob.miranda@csueastbay.edu
  Coby Morvinski:
    name: Coby Morvinski
    affiliation: '48'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: cobym@bgu.ac.il
  Aishwarya  Muppoor:
    name: Aishwarya  Muppoor
    affiliation: '15'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: aishwaryamuppoor22@gmail.com
  F. Elif Müjdeci:
    name: F. Elif Müjdeci
    affiliation: '49'
    role:
      - Resources
      - Validation
      - Writing - review & editing
    corresponding: no
    email: mujdecifatmaelif@gmail.com
  Yngwie A. Nielsen:
    name: Yngwie A. Nielsen
    affiliation: '50'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: yan@cc.au.dk
  Juan C. Oliveros:
    name: Juan C. Oliveros
    affiliation: '51'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: joliveros@ucm.cl
  Jaš Onič:
    name: Jaš Onič
    affiliation: '41'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: onicjas@gmail.com
  Marietta  Papadatou-Pastou:
    name: Marietta  Papadatou-Pastou
    affiliation: '52'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: marietta.papadatou-pastou@seh.oxon.org
  Ishani Patel:
    name: Ishani Patel
    affiliation: '15'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: ishanipatel03@gmail.com
  Zoran Pavlović:
    name: Zoran Pavlović
    affiliation: '53'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: zoran.pavlovic@f.bg.ac.rs
  Blaž Pažon:
    name: Blaž Pažon
    affiliation: '41'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: blaz.pazon@gmail.com
  Gerit Pfuhl:
    name: Gerit Pfuhl
    affiliation: '54,55'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: gerit.pfuhl@ntnu.no
  Ekaterina Pronizius:
    name: Ekaterina Pronizius
    affiliation: '56'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: ekaterina.pronizius@univie.ac.at
  Timo B. Roettger:
    name: Timo B. Roettger
    affiliation: '35'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: timo.roettger@iln.uio.no
  Camilo R. Ronderos:
    name: Camilo R. Ronderos
    affiliation: '35'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: camilorr@uio.no
  Susana Ruiz-Fernandez:
    name: Susana Ruiz-Fernandez
    affiliation: '57'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: ruizfern@b-tu.de
  Magdalena Senderecka:
    name: Magdalena Senderecka
    affiliation: '14'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: magdalena.senderecka@uj.edu.pl
  Çağlar Solak:
    name: Çağlar Solak
    affiliation: '58'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: solakcaglar@gmail.com
  Anna Stückler:
    name: Anna Stückler
    affiliation: '50'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: asj@psy.au.dk
  Raluca D. Szekely-Copîndean:
    name: Raluca D. Szekely-Copîndean
    affiliation: '59,60'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: ralucaszekely@gmail.com
  Analí R. Taboh:
    name: Analí R. Taboh
    affiliation: '20,31'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: anali.taboh@conicet.gov.ar
  Rémi Thériault:
    name: Rémi Thériault
    affiliation: '61'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: theriault.remi@courrier.uqam.ca
  Ulrich S. Tran:
    name: Ulrich S. Tran
    affiliation: '56'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: ulrich.tran@univie.ac.at
  Fabio Trecca:
    name: Fabio Trecca
    affiliation: '50'
    role:
      - Funding acquisition
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: fabio@cc.au.dk
  José Luis Ulloa:
    name: José Luis Ulloa
    affiliation: '62'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: joseluisulloafulgeri@gmail.com
  Marton A. Varga:
    name: Marton A. Varga
    affiliation: '18'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: martonaronvarga@gmail.com
  Steven Verheyen:
    name: Steven Verheyen
    affiliation: '63'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: verheyen@essb.eur.nl
  Tijana Vesić Pavlović:
    name: Tijana Vesić Pavlović
    affiliation: '53'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: tvesic@mas.bg.ac.rs
  Giada Viviani:
    name: Giada Viviani
    affiliation: '64'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: giada.viviani@unipd.it
  Nan Wang:
    name: Nan Wang
    affiliation: '65'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: nanwanglin@gmail.com
  Kristyna Zivna:
    name: Kristyna Zivna
    affiliation: '66'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: kristyna.zivna@oushi.upol.cz
  Chen C. Yun:
    name: Chen C. Yun
    affiliation: '67'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: ccyjuncat@gmail.com
  Oliver J. Clark:
    name: Oliver J. Clark
    affiliation: '68'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: O.clark@mmu.ac.uk
  Oguz A. Acar:
    name: Oguz A. Acar
    affiliation: '69'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: oguz.acar@kcl.ac.uk
  Matúš Adamkovič:
    name: Matúš Adamkovič
    affiliation: '33,70,71'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: matho.adamkovic@gmail.com
  Giulia Agnoletti:
    name: Giulia Agnoletti
    affiliation: '31,72'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: giulia.agnoletti@outlook.com
  Atakan M. Akil:
    name: Atakan M. Akil
    affiliation: '18,73'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: akil.atakan@pte.hu
  Zainab Alsuhaibani:
    name: Zainab Alsuhaibani
    affiliation: '74'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: zaalsuhaibani@imamu.edu.sa
  Simona Amenta:
    name: Simona Amenta
    affiliation: '75'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: simona.amenta@unimib.it
  Olga A. Ananyeva:
    name: Olga A. Ananyeva
    affiliation: '76'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: oananyeva@hse.ru
  Michael Andreychik:
    name: Michael Andreychik
    affiliation: '77'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: mandreychik@fairfield.edu
  Bernhard  Angele:
    name: Bernhard  Angele
    affiliation: '78,79'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: bangele1@nebrija.es
  Danna  C. Arias Quiñones:
    name: Danna  C. Arias Quiñones
    affiliation: '80'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: dariasqu@fandm.edu
  Nwadiogo C. Arinze:
    name: Nwadiogo C. Arinze
    affiliation: '81'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: arinzenwadiogo@gmail.com
  Adrian D. Askelund:
    name: Adrian D. Askelund
    affiliation: '82,83'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: adrian.askelund@gmail.com
  Bradley J. Baker:
    name: Bradley J. Baker
    affiliation: '84'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: bradley.baker@temple.edu
  Ernest Baskin:
    name: Ernest Baskin
    affiliation: '85'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: ebaskin@sju.edu
  Luisa  Batalha:
    name: Luisa  Batalha
    affiliation: '86'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: luisa.batalha@acu.edu.au
  Carlota Batres:
    name: Carlota Batres
    affiliation: '80'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: cbatres@fandm.edu
  Maria S. Beato:
    name: Maria S. Beato
    affiliation: '87'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: msol@usal.es
  Manuel Becker:
    name: Manuel Becker
    affiliation: '88'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: manuel.becker@uni-marburg.de
  Maja Becker:
    name: Maja Becker
    affiliation: '16'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: mbecker@univ-tlse2.fr
  Maciej Behnke:
    name: Maciej Behnke
    affiliation: '89'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: macbehnke@gmail.com
  Christophe Blaison:
    name: Christophe Blaison
    affiliation: '17'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: christophe.blaison@u-paris.fr
  Anna M. Borghi:
    name: Anna M. Borghi
    affiliation: '90,91'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: anna.borghi@uniroma1.it
  Eduard Brandstätter:
    name: Eduard Brandstätter
    affiliation: '92'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: eduard.brandstaetter@jku.at
  Jacek Buczny:
    name: Jacek Buczny
    affiliation: '93'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: jbuczny@gmail.com
  Nesrin Budak:
    name: Nesrin Budak
    affiliation: '94'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: nesrin.budak@metu.edu.tr
  Álvaro  Cabana:
    name: Álvaro  Cabana
    affiliation: '95'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: acabana@psico.edu.uy
  Zhenguang G. Cai:
    name: Zhenguang G. Cai
    affiliation: '65'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: zhenguangcai@cuhk.edu.hk
  Enrique C. Canessa:
    name: Enrique C. Canessa
    affiliation: '96'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: ecanessa@uai.cl
  Ignacio Castillejo:
    name: Ignacio Castillejo
    affiliation: '97'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: jignaciocastillejo@gmail.com
  Müge Cavdan:
    name: Müge Cavdan
    affiliation: '98'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: Muege.Cavdan@psychol.uni-giessen.de
  Luca Cecchetti:
    name: Luca Cecchetti
    affiliation: '99'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: luca.cecchetti@imtlucca.it
  Sergio E. Chaigneau:
    name: Sergio E. Chaigneau
    affiliation: '96'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: sergio.chaigneau@uai.cl
  Feria X. W. Chang:
    name: Feria X. W. Chang
    affiliation: '100'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: feriachangxiuwen@gmail.com
  Christopher  R. Chartier:
    name: Christopher  R. Chartier
    affiliation: '101'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: cchartie@ashland.edu
  Sau-Chin Chen:
    name: Sau-Chin Chen
    affiliation: '102'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: pmsp96@gmail.com
  Elena Cherniaeva:
    name: Elena Cherniaeva
    affiliation: '76'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: chernyaeva.ela@gmail.com
  Morten H. Christiansen:
    name: Morten H. Christiansen
    affiliation: '50,103'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: morten@cc.au.dk
  Hu Chuan-Peng:
    name: Hu Chuan-Peng
    affiliation: '67'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: hcp4715@hotmail.com
  Patrycja Chwiłkowska:
    name: Patrycja Chwiłkowska
    affiliation: '89'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: patchw1@amu.edu.pl
  Montserrat Comesaña:
    name: Montserrat Comesaña
    affiliation: '104'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: mvila@psi.uminho.pt
  Chin Wen Cong:
    name: Chin Wen Cong
    affiliation: '105'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: chinwencong@outlook.com
  Casey Cowan:
    name: Casey Cowan
    affiliation: '106'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: casey.cowan.cc@gmail.com
  Stéphane D. Dandeneau:
    name: Stéphane D. Dandeneau
    affiliation: '107'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: sdandeneau@mun.ca
  Oana A. David:
    name: Oana A. David
    affiliation: '60'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: Oana.David@ubbcluj.ro
  William E. Davis:
    name: William E. Davis
    affiliation: '108'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: davisw4@wittenberg.edu
  Elif G. Demirag Burak:
    name: Elif G. Demirag Burak
    affiliation: '109'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: eburak@ou.edu
  Barnaby J. W. Dixson:
    name: Barnaby J. W. Dixson
    affiliation: '110,111'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: bdixson@usc.edu.au
  Hongfei Du:
    name: Hongfei Du
    affiliation: '112,113'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: dhfpsy@gmail.com
  Rod Duclos:
    name: Rod Duclos
    affiliation: '114'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: rduclos@ivey.ca
  Wouter Duyck:
    name: Wouter Duyck
    affiliation: '115'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: wouter.duyck@ugent.be
  Liudmila A. Efimova:
    name: Liudmila A. Efimova
    affiliation: '76'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: laefimova@edu.hse.ru
  Ciara Egan:
    name: Ciara Egan
    affiliation: '106'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: ciara.egan@universityofgalway.ie
  Vanessa Era:
    name: Vanessa Era
    affiliation: '90,116'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: vanessa.era@uniroma1.it
  Thomas  R. Evans:
    name: Thomas  R. Evans
    affiliation: '117'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: thomas.evans@greenwich.ac.uk
  Anna Exner:
    name: Anna Exner
    affiliation: '118'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: anna.exner@posteo.de
  Gilad Feldman:
    name: Gilad Feldman
    affiliation: '119'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: giladfel@gmail.com
  Katharina Fellnhofer:
    name: Katharina Fellnhofer
    affiliation: '120,121'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: kfellnhofer@ethz.ch
  Chiara  Fini:
    name: Chiara  Fini
    affiliation: '90'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: chiara.fini@uniroma1.it
  Sarah E. Fisher:
    name: Sarah E. Fisher
    affiliation: '101'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: sfish10art@yahoo.com
  Heather D. Flowe:
    name: Heather D. Flowe
    affiliation: '26'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: hflowe@gmail.com
  Patricia Garrido-Vásquez:
    name: Patricia Garrido-Vásquez
    affiliation: '122'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: patricia.garrido@udec.cl
  Daniele Gatti:
    name: Daniele Gatti
    affiliation: '123'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: daniele.gatti@unipv.it
  Jason Geller :
    name: Jason Geller 
    affiliation: '124'
    role:
      - Validation
      - Writing - review & editing
    corresponding: no
    email: Drjasongeller@gmail.com
  Vaitsa Giannouli:
    name: Vaitsa Giannouli
    affiliation: '125'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: giannouliv@hotmail.com
  Anna S. Gorokhova:
    name: Anna S. Gorokhova
    affiliation: '76'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: anyuta.post@gmail.com
  Lindsay M. Griener:
    name: Lindsay M. Griener
    affiliation: '126'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: ccpling@ualberta.ca
  Dmitry Grigoryev:
    name: Dmitry Grigoryev
    affiliation: '76'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: dgrigoryev@hse.ru
  Igor Grossmann:
    name: Igor Grossmann
    affiliation: '127'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: igrossma@uwaterloo.ca
  Mohammadhesam Hajighasemi:
    name: Mohammadhesam Hajighasemi
    affiliation: '128'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: mohammadhesam.hajighasemi@essec.edu
  Giacomo Handjaras:
    name: Giacomo Handjaras
    affiliation: '99'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: giacomo.handjaras@imtlucca.it
  Cathy Hauspie:
    name: Cathy Hauspie
    affiliation: '115'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: cathy.hauspie@ugent.be
  Zhiran He:
    name: Zhiran He
    affiliation: '129'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: z18839126783@163.com
  Renata M. Heilman:
    name: Renata M. Heilman
    affiliation: '60'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: renataheilman@psychology.ro 
  Amirmahdi Heydari:
    name: Amirmahdi Heydari
    affiliation: '24'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: amirmahdiheidari2020@gmail.com
  Alanna M. Hine:
    name: Alanna M. Hine
    affiliation: '106'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: alannahine@gmail.com
  Karlijn Hoyer:
    name: Karlijn Hoyer
    affiliation: '130'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: Karlijnhoyer@gmail.com
  Weronika Hryniszak:
    name: Weronika Hryniszak
    affiliation: '14'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: weronika.hryniszak@doctoral.uj.edu.pl
  Janet H.-w. Hsiao:
    name: Janet H.-w. Hsiao
    affiliation: '131'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: jhhsiao@ust.hk
  Guanxiong Huang:
    name: Guanxiong Huang
    affiliation: '132'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: g.huang@cityu.edu.hk
  Keiko Ihaya:
    name: Keiko Ihaya
    affiliation: '133'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: ihaya@fit.ac.jp
  Ewa Ilczuk:
    name: Ewa Ilczuk
    affiliation: '14'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: ewa.ilczuk@doctoral.uj.edu.pl
  Tatsunori Ishii:
    name: Tatsunori Ishii
    affiliation: '134'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: t_ishii1108@yahoo.co.jp
  Andrei Dumbravă:
    name: Andrei Dumbravă
    affiliation: '135,136'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: andrei.dumbrava@uaic.ro
  Katarzyna Jankowiak:
    name: Katarzyna Jankowiak
    affiliation: '89'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: katarzyna.jankowiak@amu.edu.pl 
  Xiaoming Jiang:
    name: Xiaoming Jiang
    affiliation: '137'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: xiaoming.jiang@shisu.edu.cn
  David C. Johnson:
    name: David C. Johnson
    affiliation: '138'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: davejohnson7@mac.com
  Rafał Jończyk:
    name: Rafał Jończyk
    affiliation: '89'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: rafal.jonczyk@amu.edu.pl
  Juhani Järvikivi:
    name: Juhani Järvikivi
    affiliation: '126'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: jarvikivi@ualberta.ca
  Laura Kaczer:
    name: Laura Kaczer
    affiliation: '20'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: laurakaczer@gmail.com
  Kevin  L. Kamermans:
    name: Kevin  L. Kamermans
    affiliation: '2'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: klkamermans@gmail.com
  Johannes A. Karl:
    name: Johannes A. Karl
    affiliation: '139'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: johannes.a.karl@gmail.com
  Alexander Karner:
    name: Alexander Karner
    affiliation: '56'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: alexander.karner@univie.ac.at
  Pavol Kačmár:
    name: Pavol Kačmár
    affiliation: '140'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: pavol.kacmar@upjs.sk
  Jacob J. Keech:
    name: Jacob J. Keech
    affiliation: '141'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: j.keech@griffith.edu.au
  M. Justin Kim:
    name: M. Justin Kim
    affiliation: '142,143'
    role:
      - Validation
      - Writing - review & editing
    corresponding: no
    email: minuekim@skku.edu
  Max Korbmacher:
    name: Max Korbmacher
    affiliation: '144,145'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: Max.korbmacher@hvl.no
  Kathrin Kostorz:
    name: Kathrin Kostorz
    affiliation: '56'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: kathrin.kostorz@univie.ac.at
  Marta Kowal:
    name: Marta Kowal
    affiliation: '146'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: marta7kowal@gmail.com
  Tomas Kratochvil:
    name: Tomas Kratochvil
    affiliation: '147'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: kratochvilt@mail.muni.cz
  Yoshihiko Kunisato:
    name: Yoshihiko Kunisato
    affiliation: '148'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: ykunisato@psy.senshu-u.ac.jp
  Anna O. Kuzminska:
    name: Anna O. Kuzminska
    affiliation: '149'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: a.kuzminska@uw.edu.pl
  Lívia Körtvélyessy:
    name: Lívia Körtvélyessy
    affiliation: '140'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: livia.kortvelyessy@upjs.sk
  Fatma E. Köse:
    name: Fatma E. Köse
    affiliation: '150,151'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: ebruates.ea@gmail.com
  Massimo Köster:
    name: Massimo Köster
    affiliation: '88'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: massimo.koester@uni-marburg.de
  Magdalena Kękuś:
    name: Magdalena Kękuś
    affiliation: '152'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: mkekus@swps.edu.pl
  Melanie Labusch:
    name: Melanie Labusch
    affiliation: '28,153'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: melanie.labusch@uv.es
  Claus Lamm:
    name: Claus Lamm
    affiliation: '56'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: claus.lamm@univie.ac.at
  Chaak Ming Lau:
    name: Chaak Ming Lau
    affiliation: '154'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: lchaakming@eduhk.hk
  Julieta Laurino:
    name: Julieta Laurino
    affiliation: '20'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: julilaurino@gmail.com
  Wilbert Law:
    name: Wilbert Law
    affiliation: '154'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: wlaw@eduhk.hk
  Giada Lettieri:
    name: Giada Lettieri
    affiliation: '99'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: giada.lettieri@imtlucca.it
  Carmel A. Levitan:
    name: Carmel A. Levitan
    affiliation: '155'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: levitan@oxy.edu
  Jackson G. Lu:
    name: Jackson G. Lu
    affiliation: '156'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: lu18@mit.edu
  Sarah E. MacPherson:
    name: Sarah E. MacPherson
    affiliation: '157'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: sarah.macpherson@ed.ac.uk
  Klara Malinakova:
    name: Klara Malinakova
    affiliation: '66'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: klara.malinakova@oushi.upol.cz
  Diego Manriquez-Robles:
    name: Diego Manriquez-Robles
    affiliation: '158'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: dmanriquezrobles@gmail.com
  Nicolás Marchant:
    name: Nicolás Marchant
    affiliation: '96'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: nicolas.marchant@edu.uai.cl
  Marco Marelli:
    name: Marco Marelli
    affiliation: '75'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: marco.marelli@unimib.it
  Martín Martínez:
    name: Martín Martínez
    affiliation: '159'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: tininmartinez@gmail.com
  Molly F. Matthews:
    name: Molly F. Matthews
    affiliation: '127'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: m8matthe@uwaterloo.ca
  Alan D. A. Mattiassi:
    name: Alan D. A. Mattiassi
    affiliation: '160'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: alan.mattiassi@gmail.com
  Josefina Mattoli-Sánchez:
    name: Josefina Mattoli-Sánchez
    affiliation: '161'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: josefina.mattoli_s@mail.udp.cl
  Claudia  Mazzuca:
    name: Claudia  Mazzuca
    affiliation: '90'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: claudia.mazzuca@uniroma1.it
  David P. McGovern:
    name: David P. McGovern
    affiliation: '139'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: david.p.mcgovern@dcu.ie
  Zdenek Meier:
    name: Zdenek Meier
    affiliation: '66'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: zdenek.meier@oushi.upol.cz
  Filip Melinscak:
    name: Filip Melinscak
    affiliation: '56'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: filip.melinscak@univie.ac.at
  Michal Misiak:
    name: Michal Misiak
    affiliation: '146,162'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: michal.misiak@uwr.edu.pl
  Luis C. P. Monteiro:
    name: Luis C. P. Monteiro
    affiliation: '163'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: luis.monteiro@icb.ufpa.br
  David Moreau:
    name: David Moreau
    affiliation: '164'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: d.moreau@auckland.ac.nz
  Sebastian Moreno:
    name: Sebastian Moreno
    affiliation: '96'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: sebastian.moreno.araya@gmail.com
  Kate  E. Mulgrew:
    name: Kate  E. Mulgrew
    affiliation: '110'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: kmulgrew@usc.edu.au
  Dominique Muller:
    name: Dominique Muller
    affiliation: '36,37,165'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: dominique.muller@univ-grenoble-alpes.fr
  Tamás Nagy:
    name: Tamás Nagy
    affiliation: '18'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: nagy.tamas@ppk.elte.hu
  Marcin Naranowicz:
    name: Marcin Naranowicz
    affiliation: '89'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: marcin.naranowicz@amu.edu.pl
  Izuchukwu L. G. Ndukaihe:
    name: Izuchukwu L. G. Ndukaihe
    affiliation: '81'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: ndukaihe.izuchukwu@funai.edu.ng
  Maital Neta:
    name: Maital Neta
    affiliation: '166'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: mneta2@unl.edu
  Lukas Novak:
    name: Lukas Novak
    affiliation: '66'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: lukas.novak@oushi.upol.cz
  Chisom E. Ogbonnaya:
    name: Chisom E. Ogbonnaya
    affiliation: '81'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: ogbonnaya.chisom@yahoo.com
  Jessica Jee Won Paek:
    name: Jessica Jee Won Paek
    affiliation: '167'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: jesspaek@iu.edu
  Aspasia E. Paltoglou:
    name: Aspasia E. Paltoglou
    affiliation: '68,168'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: A.Paltoglou@mmu.ac.uk
  Francisco J. Parada:
    name: Francisco J. Parada
    affiliation: '161'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: francisco.parada@udp.cl
  Adam J. Parker:
    name: Adam J. Parker
    affiliation: '169'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: adam_parker@ucl.ac.uk
  Mariola Paruzel-Czachura:
    name: Mariola Paruzel-Czachura
    affiliation: '170,171'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: mariola.paruzel-czachura@us.edu.pl
  Yuri G. Pavlov:
    name: Yuri G. Pavlov
    affiliation: '172'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: pavlovug@gmail.com
  Saeed  Paydarfard:
    name: Saeed  Paydarfard
    affiliation: '173'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: saeedpaydarfard@gmail.com
  Dominik Pegler:
    name: Dominik Pegler
    affiliation: '56'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: dominik.pegler@univie.ac.at
  Mehmet Peker:
    name: Mehmet Peker
    affiliation: '39'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: mehmet.peker@ege.edu.tr
  Manuel Perea:
    name: Manuel Perea
    affiliation: '28,153'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: manuel.perea@uv.es
  Stefan Pfattheicher:
    name: Stefan Pfattheicher
    affiliation: '50'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: sp@psy.au.dk
  John Protzko:
    name: John Protzko
    affiliation: '174'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: protzko@gmail.com
  Irina S. Prusova:
    name: Irina S. Prusova
    affiliation: '76'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: iprusova@hse.ru
  Katarzyna Pypno-Blajda:
    name: Katarzyna Pypno-Blajda
    affiliation: '170'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: katarzyna.pypno@us.edu.pl
  Zhuang Qiu:
    name: Zhuang Qiu
    affiliation: '65,175'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: zhuangharveyqiu@gmail.com
  Ulf-Dietrich Reips:
    name: Ulf-Dietrich Reips
    affiliation: '176'
    role:
      - Validation
      - Writing - review & editing
    corresponding: no
    email: reips@uni-konstanz.de
  Gianni Ribeiro:
    name: Gianni Ribeiro
    affiliation: '177,178'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: gianni.ribeiro@unisq.edu.au
  Luca Rinaldi:
    name: Luca Rinaldi
    affiliation: '123,179'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: luca.rinaldi@unipv.it
  S. Craig Roberts:
    name: S. Craig Roberts
    affiliation: '146,180'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: craig.roberts@stir.ac.uk
  Tanja C. Roembke:
    name: Tanja C. Roembke
    affiliation: '181'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: tanja.roembke@psych.rwth-aachen.de
  Marina O. Romanova:
    name: Marina O. Romanova
    affiliation: '76'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: marina.romanova.msk@gmail.com
  Robert M. Ross:
    name: Robert M. Ross
    affiliation: '182'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: robross46@gmail.com
  Jan P. Röer:
    name: Jan P. Röer
    affiliation: '183'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: jan.roeer@uni-wh.de
  Filiz Rızaoğlu:
    name: Filiz Rızaoğlu
    affiliation: '184'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: frizaoglu@pau.edu.tr
  Toni T. Saari:
    name: Toni T. Saari
    affiliation: '185'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: toni.t.saari@gmail.com
  Erika Sampaolo:
    name: Erika Sampaolo
    affiliation: '99'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: erika.sampaolo@imtlucca.it
  Anabela Caetano Santos:
    name: Anabela Caetano Santos
    affiliation: '13'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: anabela.caetano.s@gmail.com
  F. Çağlar Sarıçiçek:
    name: F. Çağlar Sarıçiçek
    affiliation: '186'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: caglarsaricicek@hotmail.com
  Kyoshiro Sasaki:
    name: Kyoshiro Sasaki
    affiliation: '187'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: kyoshiro0920@gmail.com
  Frank Scharnowski:
    name: Frank Scharnowski
    affiliation: '56'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: frank.scharnowski@univie.ac.at
  Kathleen Schmidt:
    name: Kathleen Schmidt
    affiliation: '101'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: kschmi13@ashland.edu
  Amir Sepehri:
    name: Amir Sepehri
    affiliation: '128'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: sepehri@essec.edu
  Halid O. Serçe:
    name: Halid O. Serçe
    affiliation: '188'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: halidoguz.serce@bahcesehir.edu.tr
  A. T. Sevincer:
    name: A. T. Sevincer
    affiliation: '189'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: timur.sevincer@leuphana.de
  Cynthia S. Q. Siew:
    name: Cynthia S. Q. Siew
    affiliation: '100'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: cynthia@nus.edu.sg
  Matilde E. Simonetti:
    name: Matilde E. Simonetti
    affiliation: '181'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: simonetti@psych.rwth-aachen.de
  Miroslav Sirota:
    name: Miroslav Sirota
    affiliation: '190'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: msirota@essex.ac.uk
  Agnieszka Sorokowska:
    name: Agnieszka Sorokowska
    affiliation: '146'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: sorokowska@gmail.com
  Piotr Sorokowski:
    name: Piotr Sorokowski
    affiliation: '146'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: sorokowskipiotr@yahoo.co.uk
  Ian D. Stephen:
    name: Ian D. Stephen
    affiliation: '78'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: stepheni@bournemouth.ac.uk
  Laura M. Stevens:
    name: Laura M. Stevens
    affiliation: '26'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: lms825@student.bham.ac.uk
  Suzanne L. K. Stewart:
    name: Suzanne L. K. Stewart
    affiliation: '191'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: s.stewart@chester.ac.uk
  David Steyrl:
    name: David Steyrl
    affiliation: '56'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: david.steyrl@univie.ac.at
  Stefan Stieger:
    name: Stefan Stieger
    affiliation: '192'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: stefan.stieger@kl.ac.at
  Anna Studzinska:
    name: Anna Studzinska
    affiliation: '193'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: studzinna@gmail.com
  Mar Suarez:
    name: Mar Suarez
    affiliation: '87'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: marsuarez@usal.es
  Anna Szala:
    name: Anna Szala
    affiliation: '194,195'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: szala@oakland.edu
  Arnaud Szmalec:
    name: Arnaud Szmalec
    affiliation: '115,196'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: arnaud.szmalec@uclouvain.be
  Daniel Sznycer:
    name: Daniel Sznycer
    affiliation: '197'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: daniel.sznycer@okstate.edu
  Ewa Szumowska:
    name: Ewa Szumowska
    affiliation: '14,198'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: ewa.szumowska@uj.edu.pl
  Sinem Söylemez:
    name: Sinem Söylemez
    affiliation: '58'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: ssinemsoylemez@gmail.com
  Bahadır Söylemez:
    name: Bahadır Söylemez
    affiliation: '184'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: bsoylemez@pau.edu.tr
  Kaito Takashima:
    name: Kaito Takashima
    affiliation: '199'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: ktaaa331@gmail.com
  Christian K. Tamnes:
    name: Christian K. Tamnes
    affiliation: '35'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: c.k.tamnes@psykologi.uio.no
  Joel  C. R. Tan:
    name: Joel  C. R. Tan
    affiliation: '100'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: joeltancr@u.nus.edu
  Chengxiang Tang:
    name: Chengxiang Tang
    affiliation: '200'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: tang.chengxiang@gmail.com
  Peter  Tavel:
    name: Peter  Tavel
    affiliation: '66'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: peter.tavel@oushi.upol.cz
  Julian Tejada:
    name: Julian Tejada
    affiliation: '30'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: jtejada@academico.ufs.br
  Benjamin C. Thompson:
    name: Benjamin C. Thompson
    affiliation: '201'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: bcthompson5@crimson.ua.edu
  Jake  G. Tiernan:
    name: Jake  G. Tiernan
    affiliation: '139'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: jaketiernan0@gmail.com
  Vicente Torres-Muñoz:
    name: Vicente Torres-Muñoz
    affiliation: '62'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: vicentetomu@gmail.com
  Anna  K. Touloumakos:
    name: Anna  K. Touloumakos
    affiliation: '202'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: annatouloumakos@gmail.com
  Bastien Trémolière:
    name: Bastien Trémolière
    affiliation: '16,203'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: bastien.tremoliere@univ-tlse2.fr
  Monika Tschense:
    name: Monika Tschense
    affiliation: '189'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: monika.tschense@leuphana.de
  Belgüzar N. Türkan:
    name: Belgüzar N. Türkan
    affiliation: '204'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: turkan.nilay@gmail.com
  Miguel A. Vadillo:
    name: Miguel A. Vadillo
    affiliation: '97'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: miguel.vadillo@uam.es
  Caterina Vannucci:
    name: Caterina Vannucci
    affiliation: '99'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: caterina.vannucci@imtlucca.it
  Michael E. W. Varnum:
    name: Michael E. W. Varnum
    affiliation: '205'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: mvarnum@asu.edu
  Martin R. Vasilev:
    name: Martin R. Vasilev
    affiliation: '169'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: m.vasilev@ucl.ac.uk
  Leigh Ann Vaughn:
    name: Leigh Ann Vaughn
    affiliation: '206'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: Lvaughn@ithaca.edu
  Fanny Verkampt:
    name: Fanny Verkampt
    affiliation: '207'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: fanny.verkampt@univ-cotedazur.fr
  Liliana M. Villar:
    name: Liliana M. Villar
    affiliation: '174,208'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: Liliana.m.villar@my.ccsu.edu
  Sebastian Wallot:
    name: Sebastian Wallot
    affiliation: '189'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: sebastian.wallot@leuphana.de
  Lijun Wang:
    name: Lijun Wang
    affiliation: '209'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: wanglijun239@163.com
  Ke Wang:
    name: Ke Wang
    affiliation: '210'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: wangk@darden.virginia.edu
  Glenn P. Williams:
    name: Glenn P. Williams
    affiliation: '211'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: glenn.williams@northumbria.ac.uk
  David Willinger:
    name: David Willinger
    affiliation: '192'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: david.willinger@kl.ac.at
  Kelly Wolfe:
    name: Kelly Wolfe
    affiliation: '157,212'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: k.wolfe@hw.ac.uk
  Alexandra S. Wormley:
    name: Alexandra S. Wormley
    affiliation: '205,213'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: awormley@umich.edu
  Yuki Yamada:
    name: Yuki Yamada
    affiliation: '199'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: yamadayuk@gmail.com
  Yunkai Yang:
    name: Yunkai Yang
    affiliation: '129'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: yykaiii@outlook.com
  YUWEI ZHOU:
    name: YUWEI ZHOU
    affiliation: '154'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: s1147972@s.eduhk.hk
  Mengfan Zhang:
    name: Mengfan Zhang
    affiliation: '56'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: mengfan.zhang@univie.ac.at
  Wang Zheng:
    name: Wang Zheng
    affiliation: '214'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: zhengwangpsy@163.com
  Yueyuan Zheng:
    name: Yueyuan Zheng
    affiliation: '131'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: yyzheng@ust.hk
  Chenghao Zhou:
    name: Chenghao Zhou
    affiliation: '215'
    role:
      - Resources
      - Writing - review & editing
    corresponding: no
    email: chenghao.zhou@nyu.edu
  Radka Zidkova:
    name: Radka Zidkova
    affiliation: '66'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: radka.zidkova@oushi.upol.cz.
  Nina  M. Zumbrunn:
    name: Nina  M. Zumbrunn
    affiliation: '139'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: nina.zumbrunn3@mail.dcu.ie
  Ogeday Çoker:
    name: Ogeday Çoker
    affiliation: '184'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: ogedcoker@gmail.com
  Sami Çoksan:
    name: Sami Çoksan
    affiliation: '114,216'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: scoksan@uwo.ca
  Sezin Öner:
    name: Sezin Öner
    affiliation: '186'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: sezin.oner@khas.edu.tr
  Asil A. Özdoğru:
    name: Asil A. Özdoğru
    affiliation: '217,218'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: asil.ozdogru@marmara.edu.tr
  Seda M. Şahin:
    name: Seda M. Şahin
    affiliation: '94'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: sahins@metu.edu.tr
  Dauren Kasanov:
    name: Dauren Kasanov
    affiliation: '42'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: dauren.kasa@gmail.com 
  Alexios Arvanitis:
    name: Alexios Arvanitis
    affiliation: '219'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: a.arvanitis@uoc.gr
  Cameron Brick:
    name: Cameron Brick
    affiliation: '130'
    role:
      - Validation
      - Writing - review & editing
    corresponding: no
    email: c.brick@uva.nl
  Melissa F. Colloff:
    name: Melissa F. Colloff
    affiliation: '26'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: m.colloff@bham.ac.uk
  Albina Gallyamova:
    name: Albina Gallyamova
    affiliation: '76'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: albgallyamova@gmail.com
  Christopher Koch:
    name: Christopher Koch
    affiliation: '220'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: ckoch@georgefox.edu
  Ivan Ropovik:
    name: Ivan Ropovik
    affiliation: '221,222'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: ivan.ropovik@gmail.com
  Yucheng C. Zhang:
    name: Yucheng C. Zhang
    affiliation: '223'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: yucheng.eason.zhang@gmail.com
  Xingxing Zhou:
    name: Xingxing Zhou
    affiliation: '224'
    role:
      - Investigation
      - Writing - review & editing
    corresponding: no
    email: zhouxingxing@gdaas.cn
  Sneh Patel:
    name: Sneh Patel
    affiliation: '15'
    role:
      - Investigation
      - Resources
      - Writing - review & editing
    corresponding: no
    email: snehusa1@gmail.com
  Jordan W. Suchow:
    name: Jordan W. Suchow
    affiliation: '225'
    role:
      - Validation
      - Writing - review & editing
    corresponding: no
    email: jws@stevens.edu
  Savannah C. Lewis:
    name: Savannah C. Lewis
    affiliation: '101,201'
    role:
      - Investigation
      - Project administration
      - Supervision
      - Writing - review & editing
    corresponding: no
    email: slewis5920@gmail.com

affiliation:
  - id: 1
    institution: Harrisburg University of Science and Technology
  - id: 2
    institution: Independent Researcher
  - id: 3
    institution: Leiden University
  - id: 4
    institution: Aalborg University
  - id: 5
    institution: Stanford University
  - id: 6
    institution: Christ University
  - id: 7
    institution: University of Exeter
  - id: 8
    institution: University of Padova
  - id: 9
    institution: Midwestern State University
  - id: 10
    institution: Goethe University Frankfurt
  - id: 11
    institution: Massachusetts General Hospital
  - id: 12
    institution: Harvard Medical School
  - id: 13
    institution: University Institute of Lisbon
  - id: 14
    institution: Jagiellonian University
  - id: 15
    institution: Nova Southeastern University
  - id: 16
    institution: University of Toulouse
  - id: 17
    institution: Paris Cité University
  - id: 18
    institution: ELTE Eötvös Loránd University
  - id: 19
    institution: Royal Commission for Jubail and Yanbu
  - id: 20
    institution: University of Buenos Aires
  - id: 21
    institution: University of Palermo
  - id: 22
    institution: Government College University
  - id: 23
    institution: Thammasat University
  - id: 24
    institution: University of Tehran
  - id: 25
    institution: Prince Sultan University
  - id: 26
    institution: University of Birmingham
  - id: 27
    institution: University of Leicester
  - id: 28
    institution: University of València
  - id: 29
    institution: Federal University of Uberlândia
  - id: 30
    institution: Federal University of Sergipe
  - id: 31
    institution: Torcuato Di Tella University
  - id: 32
    institution: FOM University of Applied Sciences
  - id: 33
    institution: Slovak Academy of Sciences
  - id: 34
    institution: Unaffiliated Researcher
  - id: 35
    institution: University of Oslo
  - id: 36
    institution: University of Grenoble Alpes
  - id: 37
    institution: University Savoie Mont Blanc
  - id: 38
    institution: Izmir Katip Celebi University
  - id: 39
    institution: Ege University
  - id: 40
    institution: University of Trnava
  - id: 41
    institution: University of Ljubljana
  - id: 42
    institution: Ural Federal University
  - id: 43
    institution: University of Brasília
  - id: 44
    institution: University of Warwick
  - id: 45
    institution: Illinois Institute of Technology
  - id: 46
    institution: The Hong Kong Polytechnic University
  - id: 47
    institution: California State University - East Bay
  - id: 48
    institution: Ben-Gurion University of the Negev
  - id: 49
    institution: Bilkent University
  - id: 50
    institution: Aarhus University
  - id: 51
    institution: Catholic University of Maule
  - id: 52
    institution: National and Kapodistrian University of Athens
  - id: 53
    institution: University of Belgrade
  - id: 54
    institution: UiT The Arctic University of Norway
  - id: 55
    institution: Norwegian University of Science and Technology
  - id: 56
    institution: University of Vienna
  - id: 57
    institution: Brandenburg University of Technology Cottbus-Senftenberg
  - id: 58
    institution: Manisa Celal Bayar University
  - id: 59
    institution: Romanian Academy
  - id: 60
    institution: Babeș-Bolyai University
  - id: 61
    institution: University of Quebec in Montreal
  - id: 62
    institution: University of Talca
  - id: 63
    institution: Erasmus University Rotterdam
  - id: 64
    institution: University of Padua
  - id: 65
    institution: The Chinese University of Hong Kong
  - id: 66
    institution: Palacký University Olomouc
  - id: 67
    institution: Nanjing Normal University
  - id: 68
    institution: Manchester Metropolitan University
  - id: 69
    institution: King's College London
  - id: 70
    institution: Charles University
  - id: 71
    institution: University of Jyväskylä
  - id: 72
    institution: Universidad Favaloro
  - id: 73
    institution: University of Pécs
  - id: 74
    institution: Imam Mohammad Ibn Saud Islamic University
  - id: 75
    institution: University of Milano-Bicocca
  - id: 76
    institution: National Research University Higher School of Economics
  - id: 77
    institution: Fairfield University
  - id: 78
    institution: Bournemouth University
  - id: 79
    institution: Antonio de Nebrija University
  - id: 80
    institution: Franklin and Marshall College
  - id: 81
    institution: Alex Ekwueme Federal University
  - id: 82
    institution: Lovisenberg Diaconal Hospital
  - id: 83
    institution: Norwegian Institute of Public Health
  - id: 84
    institution: Temple University
  - id: 85
    institution: Saint Joseph's University
  - id: 86
    institution: Australian Catholic University
  - id: 87
    institution: University of Salamanca
  - id: 88
    institution: University of Marburg
  - id: 89
    institution: Adam Mickiewicz University
  - id: 90
    institution: Sapienza University of Rome
  - id: 91
    institution: Italian Research Council
  - id: 92
    institution: Johannes Kepler University Linz
  - id: 93
    institution: Vrije Universiteit Amsterdam
  - id: 94
    institution: Middle East Technical University
  - id: 95
    institution: University of the Republic
  - id: 96
    institution: University of Adolfo Ibáñez
  - id: 97
    institution: Autonomous University of Madrid
  - id: 98
    institution: Justus Liebig University Giessen
  - id: 99
    institution: IMT School for Advanced Studies
  - id: 100
    institution: National University of Singapore
  - id: 101
    institution: Ashland University
  - id: 102
    institution: Tzu-Chi University
  - id: 103
    institution: Cornell University
  - id: 104
    institution: University of Minho
  - id: 105
    institution: Wawasan Open University
  - id: 106
    institution: University of Galway
  - id: 107
    institution: Memorial University of Newfoundland
  - id: 108
    institution: Wittenberg University
  - id: 109
    institution: University of Oklahoma
  - id: 110
    institution: University of the Sunshine Coast
  - id: 111
    institution: The University of Queensland Brisbane
  - id: 112
    institution: Beijing Normal University at Zhuhai
  - id: 113
    institution: Beijing Normal University
  - id: 114
    institution: Western University
  - id: 115
    institution: Ghent University
  - id: 116
    institution: IRCCS Santa Lucia Foundation
  - id: 117
    institution: University of Greenwich
  - id: 118
    institution: Ruhr University Bochum
  - id: 119
    institution: University of Hong Kong
  - id: 120
    institution: ETH Zürich
  - id: 121
    institution: Research and Innovation Management GmbH
  - id: 122
    institution: University of Concepción
  - id: 123
    institution: University of Pavia
  - id: 124
    institution: Boston College
  - id: 125
    institution: Hellenic Open University
  - id: 126
    institution: University of Alberta
  - id: 127
    institution: University of Waterloo
  - id: 128
    institution: ESSEC Business School
  - id: 129
    institution: Henan University
  - id: 130
    institution: University of Amsterdam
  - id: 131
    institution: Hong Kong University of Science and Technology
  - id: 132
    institution: City University of Hong Kong
  - id: 133
    institution: Fukuoka Institute of Technology
  - id: 134
    institution: Japan Women's University
  - id: 135
    institution: George I.M. Georgescu Institute of Cardiovascular Diseases
  - id: 136
    institution: Alexandru Ioan Cuza University
  - id: 137
    institution: Shanghai International Studies University
  - id: 138
    institution: City University of New York
  - id: 139
    institution: Dublin City University
  - id: 140
    institution: Pavol Jozef Šafárik University
  - id: 141
    institution: Griffith University
  - id: 142
    institution: Sungkyunkwan University
  - id: 143
    institution: Institute for Basic Science
  - id: 144
    institution: Western Norway University of Applied Sciences
  - id: 145
    institution: Mohn Medical Imaging and Visualization Centre
  - id: 146
    institution: University of Wrocław
  - id: 147
    institution: Masaryk University
  - id: 148
    institution: Senshu University
  - id: 149
    institution: University of Warsaw
  - id: 150
    institution: Aydın Adnan Menderes University
  - id: 151
    institution: Durham University
  - id: 152
    institution: SWPS University
  - id: 153
    institution: Nebrija University
  - id: 154
    institution: The Education University of Hong Kong
  - id: 155
    institution: Occidental College
  - id: 156
    institution: Massachusetts Institute of Technology
  - id: 157
    institution: University of Edinburgh
  - id: 158
    institution: Catholic University of Temuco
  - id: 159
    institution: University of Navarra
  - id: 160
    institution: University of Florence
  - id: 161
    institution: Diego Portales University
  - id: 162
    institution: University of Oxford
  - id: 163
    institution: Federal University of Pará
  - id: 164
    institution: University of Auckland
  - id: 165
    institution: University Institute of France
  - id: 166
    institution: University of Nebraska-Lincoln
  - id: 167
    institution: Indiana University
  - id: 168
    institution: Oxford Brookes University
  - id: 169
    institution: University College London
  - id: 170
    institution: University of Silesia
  - id: 171
    institution: University of Pennsylvania
  - id: 172
    institution: University of Tuebingen
  - id: 173
    institution: Shahid Beheshti University
  - id: 174
    institution: Central Connecticut State University
  - id: 175
    institution: City University of Macau
  - id: 176
    institution: University of Konstanz
  - id: 177
    institution: The University of Queensland
  - id: 178
    institution: University of Southern Queensland
  - id: 179
    institution: IRCCS Mondino Foundation
  - id: 180
    institution: University of Stirling
  - id: 181
    institution: RWTH Aachen University
  - id: 182
    institution: Macquarie University
  - id: 183
    institution: Witten/Herdecke University
  - id: 184
    institution: Pamukkale University
  - id: 185
    institution: University of Helsinki
  - id: 186
    institution: Kadir Has University
  - id: 187
    institution: Kansai University
  - id: 188
    institution: Bahçeşehir University
  - id: 189
    institution: Leuphana University Lüneburg
  - id: 190
    institution: University of Essex
  - id: 191
    institution: University of Chester
  - id: 192
    institution: Karl Landsteiner University of Health Sciences
  - id: 193
    institution: Icam School of Engineering
  - id: 194
    institution: Polish Academy of Sciences
  - id: 195
    institution: Nicolaus Copernicus University
  - id: 196
    institution: Catholic University of Louvain
  - id: 197
    institution: Oklahoma State University
  - id: 198
    institution: University of Maryland
  - id: 199
    institution: Kyushu University
  - id: 200
    institution: Beijing Jiaotong University
  - id: 201
    institution: The University of Alabama - Tuscaloosa
  - id: 202
    institution: Panteion University of Social and Political Science
  - id: 203
    institution: University of Quebec at Trois-Rivières
  - id: 204
    institution: Trier University
  - id: 205
    institution: Arizona State University
  - id: 206
    institution: Ithaca College
  - id: 207
    institution: Côte d’Azur University
  - id: 208
    institution: Southern New Hampshire University
  - id: 209
    institution: Wuhan University of Technology
  - id: 210
    institution: University of Virginia
  - id: 211
    institution: Northumbria University
  - id: 212
    institution: Heriot-Watt University
  - id: 213
    institution: University of Michigan
  - id: 214
    institution: East China Normal University
  - id: 215
    institution: New York University
  - id: 216
    institution: Erzurum Technical University
  - id: 217
    institution: Marmara University
  - id: 218
    institution: Üsküdar University
  - id: 219
    institution: University of Crete
  - id: 220
    institution: George Fox University
  - id: 221
    institution: Charles University in Prague
  - id: 222
    institution: Czech Academy of Sciences
  - id: 223
    institution: University of Southampton
  - id: 224
    institution: Guangdong Academy of Agricultural Science
  - id: 225
    institution: Stevens Institute of Technology

authornote: |
  Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.

  Enter author note here.

abstract: |
  One or two sentences providing a **basic introduction** to the field,  comprehensible to a scientist in any discipline.
  Two to three sentences of **more detailed background**, comprehensible  to scientists in related disciplines.
  One sentence clearly stating the **general problem** being addressed by  this particular study.
  One sentence summarizing the main result (with the words "**here we show**" or their equivalent).
  Two or three sentences explaining what the **main result** reveals in direct comparison to what was thought to be the case previously, or how the  main result adds to previous knowledge.
  One or two sentences to put the results into a more **general context**.
  Two or three sentences to provide a **broader perspective**, readily comprehensible to a scientist in any discipline.
  
  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "keywords"
wordcount         : "X"

bibliography      : "r-references.bib"

floatsintext      : no
linenumbers       : yes
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no

classoption       : "man"
output            : papaja::apa6_docx
---

```{r setup, include = FALSE}
library("papaja")
r_refs("r-references.bib")
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```



# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

## Material

## Procedure

## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.


# Results

# Discussion


\newpage

# References

::: {#refs custom-style="Bibliography"}
:::
